- pystac/catalog.py
- pystac/collection.py
- pystac/item.py
- pystac/label.py
- pystac/link.py
- tests/data-files/itemcollections/sample-item-collection.json
- tests/test_item.py
- tests/utils.py
Add's a 'collection' property to the `Item` class
- 'collection' is the id of the collection to which the item belongs
- Optional parameter
- property is updated when `set_collection` is called
closes #23
> add collection property

- pystac/collection.py
- pystac/item.py
- pystac/utils.py
- tests/test_item.py
> Modified output datetime strings to ISO8601.

- pystac/item.py
- pystac/label.py
- tests/test_eo.py
- tests/test_item.py
- tests/test_label.py
> Set asset owner to item when reading in items.

- pystac/eo.py
fix erroneous change to styling in EO script
> revert eo styling

- README.md
- docs/concepts.rst
Some small fixes and additions to docs in preparation for the 0.4 release.
> Update README and documentation in prep for 0.4 release.

- README.md
- docs/api.rst
- docs/concepts.rst
- docs/index.rst
- docs/quickstart.ipynb
- docs/tutorials/how-to-create-stac-catalogs.ipynb
- docs/tutorials/pystac-introduction.ipynb
- pystac/serialization/migrate.py
- tests/extensions/test_eo.py
This updates some version strings in the READ and docs.
Also, migrate the EO extension to account for changes in the 1.0.0-beta.2 upgrade.
> Update docs to PySTAC 0.5.0-RC1/STAC v1.0.0-beta.2

- pystac/version.py
Update version to bugfix 0.5.1
> Version 0.5.1

- README.md
Also README link changes to reflect org move.
> Add codecov badge.

- pystac/collection.py
- tests/test_collection.py
This refactors the code in ``Collection.update_extent_from_items`` into a static method on Extent so that the logic can be used in the case where a user has items but not (yet) a collection. This is useful if you are building a Collection from a set of Items, in that you can do:
```python
items = ???
extent = pystac.Extent.from_items(items)
collection = Collection(id="collection_id", description="a description", extent=extent)
collection.add_items(items)
```
> Add 'from_items' to Extent

- pystac/collection.py
> Collection TemporalExtent can be open ended

- .github/pull_request_template.md
- docs/contributing.rst
Also add some docs around adding changelog entries.
> Add a PR template

- CHANGELOG.md
Update the CHANGELOG with changes from #272 
> Update CHANGELOG for #272

- CHANGELOG.md
- pystac/version.py
Update version to 0.5.5 in preparation for release
> Version 0.5.5

- pystac/stac_io.py
> Fix comment spelling mistake

- pystac/extensions/eo.py
- pystac/extensions/file.py
- pystac/extensions/label.py
- pystac/extensions/pointcloud.py
- pystac/extensions/projection.py
- pystac/extensions/sar.py
- pystac/extensions/sat.py
- pystac/extensions/scientific.py
- pystac/extensions/single_file_stac.py
- pystac/extensions/timestamps.py
- pystac/extensions/version.py
- pystac/extensions/view.py
None
Extensions move to https://github.com/stac-extensions
> Link to the new extension location at https://github.com/stac-extensions

- CHANGELOG.md
- pystac/version.py
Merge beta.2 changes back into main branch.
I should have done this before merging into the version branch... lesson learned!
> v1.0.0 beta.2 merge to main

- pystac/cache.py
- pystac/layout.py
Found with pytype.
- [] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/develop/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.
> cache.py, layout.py: Add missing Optional type annotations

- tests/extensions/test_view.py
> tests: Fix test class name

- scripts/test
It's already configured in .coveragerc.
> refactor: Don't override source in test script

- tests/test_item.py
> refactor: Simplify assertion

- pystac/serialization/identify.py
> refactor: Join arithmetic comparisons

- pystac/cache.py
- pystac/catalog.py
- pystac/validation/stac_validator.py
> refactor: Remove redundant parentheses

- pystac/extensions/base.py
- pystac/extensions/hooks.py
- pystac/layout.py
- pystac/stac_io.py
- pystac/stac_object.py
- pystac/summaries.py
- pystac/validation/schema_uri_map.py
- pystac/validation/stac_validator.py
> refactor: Use `NotImplemented`/`NotImplementedError` as per docs

- pystac/link.py
> refactor: Inline `dict` update

- pystac/collection.py
- pystac/extensions/timestamps.py
> refactor: Don't change name of import if unnecessary

- pystac/extensions/projection.py
> chore: Remove unused constructor

- docs/conf.py
- docs/contributing.rst
- docs/make.bat
- docs/tutorials/creating-a-landsat-stac.ipynb
- docs/tutorials/how-to-create-stac-catalogs.ipynb
- pystac/catalog.py
- pystac/collection.py
- pystac/extensions/projection.py
- tests/data-files/examples/1.0.0/README.md
> docs: Use HTTPS links to external sites

- CHANGELOG.md
- pystac/version.py
Update version and CHANGELOG for 1.0.0 release!
> Bump to v1.0.0

- CHANGELOG.md
- setup.py
> exclude tests from package distribution

- CHANGELOG.md
- pystac/version.py
N/A
Updates library version to 1.3.0.
> Changes for v1.3.0 release

- CHANGELOG.md
- pystac/version.py
Update package version and CHANGELOG to support v1.5.0 release.
> Changes to support v1.5.0 release

- CHANGELOG.md
- pystac/version.py
Updates to CHANGELOG and package version for v1.6.0 release
> Change to support v1.6.0 release

- CHANGELOG.md
- pystac/version.py
Bump package version for patch release.
> Bump package to v1.6.1

- docs/conf.py
- docs/index.rst
- requirements-docs.txt
**Related Issue(s):** Closes #868 
**Before**
**After**
> Replace sphinx-panel with sphinx-design

- CHANGELOG.md
- pystac/version.py
> Release v1.7.1

- benchmarks/_util.py
- pystac/utils.py
- tests/utils/stac_io_mock.py
Hopefully this should resolve the failing checks as of mypy 1.7
> Tidy up type checking

- pystac/stac_io.py
- Flagged in #1353
Tweak to the documentation of the `retry` attribute of `RetryStacIO`. Doesn't need a changelog.
> Documentation for retry attribute

- MANIFEST.in
> Include v1.1.0 in MANIFEST.in

- CHANGELOG.md
- pystac/link.py
- tests/test_link.py
> fix: use application/geo+json for item links
