stac-utils/pystac

.travis.yml
requirements.txt
setup.py

Putting python-dateutils directly in install_requires is simpler, allows code and a file to be deleted, and is more aligned with the guidance of the python packaging authority. See https://github.com/pypa/sampleproject/blob/master/setup.py#L143-L149.
I've also made it so that the testing server installs pystac before running the tests. Not only does this pull in the requirement listed in setup.py, it also checks that the package is installable, and tests the code as it would be run in production.

Simplify install_requires

---

pystac/eo.py
pystac/item.py
tests/test_eo.py
tests/test_item.py

Overview
----
This PR makes the API around setting an owning item more obvious, and also refers to an actually existing property in `get_absolute_href` for `Asset`s.
Testing
-----
- tests

Be consistent about owner vs item for owning item

---

README.md
tests/test_utils.py

The link to STAC's site was wrong and pointing to a non-existing address.
https://stacgeo.org => https://stacspec.org
PS: Also changed test case URLs just to keep the consistency.

Fix link to STAC's site

---

.travis.yml

Installing the dev dependencies on travis produces the message:
> PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.8
Remove the 3.4 build as it's not strictly necessary as a quick fix.

Remove 3.4 build as it conflicts with dev dependencies

---

pystac/media_type.py

Replace the `vnd.` media types for GeoTIFF and COGs with the ones contained in [the media types section of the stac spec](https://github.com/radiantearth/stac-spec/blob/v0.8.1/item-spec/item-spec.md#media-types).

Updated MediaTypes to reflect correct GeoTIFF and COG names

---

pystac/utils.py
tests/test_utils.py

The make_absolute_href and make_relative_href methods workfed for
posix paths, but windows path broke the logic. This change accounts
for those paths and adds unit tests to test windows paths.
Fixes #62

Fix utils to work with windows paths.

---

pystac/utils.py
tests/test_item.py
tests/test_utils.py

It looks like the fix for #56 got closer to being able to represent dates as [RFC-3339](https://tools.ietf.org/html/rfc3339#section-5.6) formatted strings.  However, it looks like any `tzinfo` in the provided datetime is ignored.  So the current `utils.datetime_to_str()` function works for timezone naive datetimes, but not for timezone aware datetimes.
This branch proposes to treat timezone naive datetimes as UTC datetimes (in line with the current assumptions) but respects any `tzinfo` in the provided datetime.

Respect tzinfo in the provided datetime

---

pystac/catalog.py
pystac/collection.py
tests/test_catalog.py

The clone methods on catalog and collection create a new version of the STAC object and set the links on the clone manually. The problem with this is that the constructor of the Catalog sets the root link to itself - this is because a root link is required on a catalog, so a new instance should always link to itself as the root. This PR adds some additional logic to ensure that there is only one root link set in the clone. If the Catalog's root link is set to itself, then the root link of the clone will be set to the clone.
Fixes #63

Fixed catalog and collection clone logic to avoid dupe root link

---

pystac/serialization/identify.py
tests/data-files/examples/0.7.0/extensions/sar/examples/sentinel1.json
tests/data-files/examples/example-info.csv

v0.7.0 items with sar extension properties are incorrectly categorized as v0.6.2 due to a rogue "not" in serialization. These properties were lists prior to v0.7.0. `sar:absolute_orbit` is most problematic, as it's the only shared attribute name between the properties that turned from list in 0.6.2 to integer in 0.7.0.
0.6.2: https://github.com/radiantearth/stac-spec/tree/v0.6.2/extensions/sar
0.7.0: https://github.com/radiantearth/stac-spec/tree/v0.7.0/extensions/sar
Test data from: https://github.com/radiantearth/stac-spec/blob/v0.7.0/extensions/sar/examples/sentinel1.json

allow v0.7.0 sar items to fit in version range

---

pystac/catalog.py
tests/test_catalog.py

The `catalog.walk` method was iterating over the iterator that is previously `yield`ed to the caller, so if the caller iterated over the children, it would empty the iterator and `walk` would not keep walking.
This fixes this issue by using a different iterator for the internal walk of the catalog's children.

Fix issue with iteration of children in catalog.walk

---

tests/data-files/examples/example-info.csv
tests/test_catalog.py

It's not super clear if "dtr" or "datetime-range" belongs in the "stac_extensions" list for the item; however, the example for the 0.8.1 STAC spec has it with "datetime-range". This fixed the examples
info so that the proper stac extension name is matched against.
The dtr extension is dropped in future releases of STAC, so this ambiguity should be less of an issue moving forward.
Also, fixed a style issue with on of the tests.

Fixed issue with datetime-range extension name in test, style fix.

---

pystac/serialization/__init__.py
tests/data-files/examples/0.8.1/extensions/pointcloud/examples/example-autzen.json
tests/data-files/examples/0.8.1/item-spec/examples/digitalglobe-sample.json
tests/data-files/examples/0.8.1/item-spec/examples/landsat8-sample.json
tests/data-files/examples/0.8.1/item-spec/examples/sample-full.json
tests/data-files/examples/0.8.1/item-spec/examples/sample.json
tests/data-files/examples/0.8.1/item-spec/examples/sentinel2-sample.json
tests/serialization/test_migrate.py

While upgrading to 0.9.0, I exposed a bug that should be fixed in the PySTAC 0.3.* series.
Also changes the migrate test to consider all examples, not just ones
that are of a previous STAC version.

Fixed issue with reading ItemCollections directly.

---

pystac/eo.py
pystac/utils.py

I was getting an error (stack trace below) running the tutorial notebook. Looks like PySTAC wasn't able to convert an item to a python dict if it didn't have a self href defined. This PR modified `make_absolute_href` to fix this issue, returning `None` rather than throwing an error.
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-8fc29b8a3af9> in <module>
1 import json
----> 2 print(json.dumps(item.to_dict(), indent=4))
~/.local/lib/python3.6/site-packages/pystac/item.py in to_dict(self, include_self_link)
178             'geometry': self.geometry,
179             'bbox': self.bbox,
--> 180             'links': [l.to_dict() for l in links],
181 …
```

fix bug in `make_absolute_href`

---

pystac/stac_object.py
tests/test_item.py

Currently PySTAC throws an error when trying to read an Item from a dict if the item does not have a root link. While that case is not STAC compliant, it still makes the most sense for this not to fail. Necessary to pass item unit tests.

fix root link bug

---

docs/api.rst
pystac/__init__.py
pystac/collection.py
pystac/eo.py
pystac/item.py
pystac/utils.py
tests/data-files/eo/eo-landsat-example.json
tests/data-files/examples/0.9.0/extensions/asset/examples/example-landsat8.json
tests/data-files/examples/0.9.0/extensions/commons/examples/landsat-item.json
tests/data-files/examples/0.9.0/item-spec/examples/CBERS_4_MUX_20181029_177_106_L4.json
tests/data-files/examples/0.9.0/item-spec/examples/digitalglobe-sample.json
tests/data-files/examples/0.9.0/item-spec/examples/landsat8-sample.json
tests/data-files/examples/0.9.0/item-spec/examples/planet-sample.json
tests/data-files/get_examples.py
tests/test_item.py

New version of #96, with cleaned up commit history
----
This PR updates pystac to comply with STAC version 0.9. It does not add new extensions but updates the existing code (as well as unit test example JSON files to work with the newest version of STAC).
Individual changes:
- updates unit test example data files so that they comply with 0.9
- adds `CommonMetadata` class which stores all common fields present in item properties that are not actual attributes of items. 
- removes specific properties from EOItems
- removes version attribute from Collections
- Changes docstring for license aregument in collections
- removes GSD and accuracy for Bands objects
- adds rolls to asset definition
- adds utility function to get bbox from geojson without needing shapely. Could be used if we want to …

Update to 0.9

---

tests/test_catalog.py

This PR removes a hardcoded temp directory from the unit tests and instead uses `TemporaryDirectory`.

Remove hard-coded tmp directory from unit tests

---

pystac/extensions/eo.py

This surfaced when trying to print out an eoextension obj:
tries to reference the ext id rather than the underlying item

fix __repr__ bug

---

.github/workflows/continuous-integration.yml
README.md

Ensure that the CI workflow is triggered when changes are pushed to the `develop` and `master` branches. In addition, this scopes the GitHub Actions badge status to the `develop` branch.
Fixes https://github.com/azavea/pystac/issues/111
---
**Testing**
I haven't come up with a good way to test this. I think that the `develop` workflow has to be activated for the `.svg?branch=develop` badge to exist.

Add primary Git branches to CI workflow

---

docs/tutorials/pystac-spacenet-tutorial.ipynb
pystac/extensions/label.py

Straightforward upgrade to STAC 0.9.0 for a catalog utilizing the Label extension, thanks @lossyrob!
Here's two _very_ minor fixes to the docs that I noticed while doing our upgrade.

Minor fixes to Label extension docs

---

CHANGELOG.md
docs/api.rst
pystac/__init__.py
pystac/extensions/__init__.py
pystac/extensions/projection.py
tests/data-files/projection/example-landsat8.json
tests/extensions/test_projection.py
tests/utils/validator.py

This adds support for the [Projection extension](https://github.com/radiantearth/stac-spec/tree/master/extensions/projection).
This PR:
- Adds the projection extension to the `pystac.extensions` package
- adds the extension identifier to `pystac.extensions.Extensions`
- registers the projection extension in the the top level `__init__.py`
- Adds unit tests for the extension, including modifying the STACValidator to validate against the extension
- Adds API docs for the extension
- Documents the change in the CHANGELOG

Add the Projection extension.

---

docs/api.rst
pystac/extensions/eo.py
pystac/extensions/label.py
pystac/extensions/view.py
pystac/item.py
pystac/version.py
tests/data-files/change_stac_version.py

Some small fixes:
- Set PySTAC version for next release to 0.5.0 (1.0.0 is targeted to happen once STAC 1.0.0 moves off of beta)
- Cleanup `Returns:` section of some pydocs
- Fix up extension docs
- Fix up some formatting

Fixup changes for 1.0.0 feature branch

---

CHANGELOG.md
docs/api.rst
pystac/__init__.py
pystac/catalog.py
pystac/item.py
pystac/serialization/identify.py
pystac/serialization/migrate.py
pystac/version.py
tests/data-files/get_examples.py
tests/serialization/test_migrate.py
tests/test_version.py
tests/utils/validator.py

This allows STAC_VERSION to be dynamically set by the user through a call to `pystac.set_stac_version` or an environment variable.
Fixes #121

Refactor STAC_VERSION to get_stac_version

---

CHANGELOG.md
pystac/serialization/__init__.py
pystac/serialization/common_properties.py
pystac/serialization/identify.py
tests/serialization/test_identify.py

Identification and migration currently uses string ordering for comparison. This doesn't work when comparing version such as `1.0.0` and `1.0.0-beta.2`. This PR ensures that those orderings utilize a version object that understands pre-release versions.

Ensure proper version ordering during identification and migration.

---

docs/concepts.rst
pystac/cache.py
pystac/catalog.py
pystac/extensions/base.py
pystac/extensions/label.py
pystac/item.py
pystac/link.py
pystac/serialization/migrate.py
pystac/stac_object.py
pystac/version.py

This PR moves the PySTAC version from 0.5.0-RC1 to 0.5.0.
It also contains some small documentation fixes.

Update PySTAC version to 0.5.0

---

docs/tutorials.rst
docs/tutorials/adding-new-and-custom-extensions.ipynb

This PR adds a tutorial on how to implement extensions in PySTAC.
This should be helpful for anyone who wants to tackle issues #29, #30, #32, #33, #34, #131, #132, #133, #134, or #134

Add tutorial on implementing extensions in PySTAC.

---

tests/serialization/test_identify.py
tests/serialization/test_migrate.py
tests/validation/test_validate.py

assertTrue(thing) -> assertEqual, assertIn, assertIsInstance

Use python unittest's checks to get better error messages on failure.

---

.github/workflows/continuous-integration.yml
requirements-dev.txt
scripts/test

Small PR to help future tracking of gains by unittests using Coverage analysis and visualization in codecov.
A codecov token needs to be added to the Repo secrets. Pipeline step is set to continue on failure to push. I wrote this mostly to assist in contributing unittests for #155 .
Signed-off-by: Tisham Dhar <tisham.dhar@ga.gov.au>

#163 enable coverage capture

---

CHANGELOG.md
pystac/collection.py
tests/test_collection.py

Add method to update collection extent object. 
creates SpatialExtent based on bbox of items
creates Temporal Extent based on datetime   + props.start_datetime, props.end_datetime 
Impliments #145

Feature/update Collection extent from Items

---

CHANGELOG.md
pystac/stac_object.py
tests/data-files/catalogs/cbers-partial/CBERS4AWFI/collection.json
tests/data-files/catalogs/cbers-partial/CBERS4MUX/collection.json
tests/data-files/catalogs/cbers-partial/CBERS4PAN10M/collection.json
tests/data-files/catalogs/cbers-partial/CBERS4PAN5M/collection.json
tests/data-files/catalogs/cbers-partial/catalog.json
tests/test_catalog.py
tests/utils/test_cases.py

There was a bug that was causing some children to get missed in the `get_children` call of the cbers catalog. This appeared based on the root link being resolved and the logic reordering the links during resolution. 
Thanks @matthewhanson and @digitaltopo for catching this.

Fix bug that caused get_children to miss some links.

---

CHANGELOG.md
docs/api.rst
pystac/__init__.py
pystac/extensions/timestamps.py
tests/data-files/timestamps/example-landsat8.json
tests/extensions/test_timestamps.py

adds `timestamps` extension
closes #135 
One question I have is about the `apply` method in `TimestampsItemExt` (and this question could be relevant to other extensions as well): if you pass null values for optional arguments defining properties that are already defined in that item, should the null value override the existing property?
So for example:
`item` already has `published` and `expired` defined. 
if i do `item.ext.timestamps.apply(unpublished=d)`, this will convert those other two properties to None. Should this be the case?

add timestamps extension

---

docs/tutorials.rst
docs/tutorials/creating-a-landsat-stac.ipynb

This PR adds a tutorial for creating a STAC of a subset of Landsat 8 data from AWS.
This tutorial:
- reads a list of scenes from AWS
- creates a subset of scenes based on a location and year
- Reads relevant metadata from the `MTL` and `ANG` files for a scene to create an Item per scene, including information for the `eo`, `projection`, and `view` extensions.
- Creates a Collection of the scene Items.
- Writes out the STAC locally
- Servers the STAC out for usage in `stac-browser`.

Add tutorial for creating Landsat 8 STAC

---

pystac/validation/stac_validator.py

Example: `jsonfor`
```
Validation failed for COLLECTION with ID [SNIP]
scientific/json-schema/schema.jsonfor STAC extension 'scientific'
```

stac_validator.py: Fix formatting in _get_error_message()

---

docs/api.rst
pystac/__init__.py
pystac/extensions/version.py
tests/extensions/test_version.py

The initial version only implements version for Items.  I still need to do version for Collections.  Also, I'm sure more tests are needed.
https://github.com/radiantearth/stac-spec/tree/dev/extensions/version

Add support for the version extension.

---

pystac/collection.py
tests/data-files/catalogs/planet-example-1.0.0-beta.2/collection.json
tests/data-files/catalogs/planet-example-1.0.0-beta.2/hurricane-harvey/catalog.json
tests/data-files/catalogs/planet-example-1.0.0-beta.2/hurricane-harvey/hurricane-harvey-0831/20170831_162740_ssc1d1/20170831_162740_ssc1d1.json
tests/data-files/catalogs/planet-example-1.0.0-beta.2/hurricane-harvey/hurricane-harvey-0831/20170831_172754_101c/20170831_172754_101c.json
tests/data-files/catalogs/planet-example-1.0.0-beta.2/hurricane-harvey/hurricane-harvey-0831/20170831_195425_SS02/20170831_195425_SS02.json
tests/data-files/catalogs/planet-example-1.0.0-beta.2/hurricane-harvey/hurricane-harvey-0831/2017831_195552_SS02/2017831_195552_SS02.json
tests/data-files/catalogs/planet-example-1.0.0-beta.2/hurricane-harvey/hurricane-harvey-0831/Houston-East-20170831-103f-100d-0f4f-RGB/Houston-East-20170831-103f-100d-0f4f-RGB.json
tests/data-files/catalogs/planet-example-1.0.0-beta.2/hurricane-harvey/hurricane-harvey-0831/catalog.json
tests/test_catalog.py
tests/utils/test_cases.py

The collection set_self_href has specific logic that will remove and add data to the root catalog's resolved object cache. This is required so that the collection cache, which is used when merging common properties into items (a pre-1.0 STAC feature), can keep proper track of the collection that are cached by href. However, if the root link is not yet resolved, this cache swapping does not need to occur. In a situation where the root was itself a collection there was an infinite loop between resolving the root link and setting it's self href, which in turn caused the not-quite-yet-resolved root link to go through the logic again.
This fix will only swap cache instances out for collections during set_self_href for root links that have already been resolved.
It adds a version of the planet …

Fix issue that can cause infinite recursion during full resolve

---

README.md
docs/tutorials/pystac-spacenet-tutorial.ipynb
pystac/collection.py
pystac/link.py
pystac/validation/stac_validator.py
requirements-dev.txt
tests/test_collection.py
tests/test_link.py
tests/validation/test_validate.py

This PR adds a few fixes and enhancements based on solving the issues raised in #197 and #198.
- Fixes the spacenet tutorial to pass in a list of bboxes to the spatial extent, rather than a single bbox.
- Changes that tutorial to validate each of the catalogs it produces.
- Fix an issue raised by the validation of the label items, where the `label_classes` property is required. This requirement is dropped in a yet-unreleased version of the schemas, so a note was added to remove after 1.0.0-beta.2's successor is released.
- Fixed an issue with `Link.get_href()`, which was throwing a bad exception if a relative link had None for it's target href.
- Allowed users to pass in a single bbox to `SpatialExtent` and interval to `TemporalExtent` to guard against the common mistake mentioned in #198 …

Fix spacenet tutorial, allow for single bbox argument to SpatialExtent, and other fixes.

---

pystac/catalog.py
tests/test_collection.py

This commit modifies the order of the logic in the Catalog.__init__ method to ensure the resolved object cache is established before a set_self_href call is made, which occurs if a non-None href is supplied. The logic of the Collection's set_self_href method requires the resolution cache be created on the object, which this change ensures.
Fixes #182

Ensure resolve object cache is set before set_self_href is called

---

pystac/utils.py
tests/test_utils.py

The logic in make_absolute_href uses os.path.abspath, which normalizes paths. This lets us translate joined paths like /home/user/../catalog.json into proper paths. However, normalizing the path will also modify the root path being joined to in ways that may not be desirable. Specifically in the case of a /vsitar/ prefix, the double slashes that are required for proper GDAL reading are removed by normalization. This commit modifies the logic in make_absolute_href to detect when the original start path is modified by a call to abspath, and if so replaces the modified version with the original version.
Fixes #180

Allow for unnormalized path prefixes like /vsitar/

---

pystac/cache.py
pystac/link.py
pystac/stac_object.py
tests/data-files/invalid/shared-id/catalog.json
tests/data-files/invalid/shared-id/test/collection.json
tests/data-files/invalid/shared-id/test/test-item-1/test-item-1.json
tests/test_cache.py
tests/test_catalog.py

This PR refactors the caching strategy used by the resolved object cache to be based on an object's self HREF if available, and if not, to use a combination of the object's and its parents' IDs.
Before this change PySTAC required IDs to be unique within a catalog. This proved to be too restrictive and produced unexpected results in several situations.
Fixes #160 
Fixes #92

Refactor caching to utilize HREFs and parent IDs

---

README.md
requirements-dev.txt
scripts/test

This PR adds running codespell to the scripts/test script, which is run by CI. This will fail PRs that have spelling mistakes. A currently empty ignore file is put into place in case codespell fails on any intentional spellings.
Fixes #200

Add codespell to CI.

---

pystac/catalog.py
pystac/collection.py
pystac/serialization/common_properties.py
tests/data-files/examples/example-info.csv
tests/data-files/examples/hand-0.8.1/010100/010100.json
tests/data-files/examples/hand-0.8.1/collection.json
tests/data-files/examples/hand-0.9.0/010100/010100.json
tests/data-files/examples/hand-0.9.0/collection.json
tests/test_catalog.py
tests/test_collection.py
tests/test_item.py

This PR fixes issues uncovered while investigating #186.
- The merge_common_properties logic was executing in the case of a 0.9.0 item that did not have the 'commons' extension implemented. This was due to a bug in the logic that didn't account for the case where `stac_extensions` was not declared in the Item.
- When the merge_common_properties logic does execute, if the collection that is referenced by the item produces a cached value that is not a Collection (for example if a collection was read in as a Catalog as described in #186), throw a more clear error than was previously being thrown.
The two other changes below relate to the caching changes made in #214:
- The logic in Catalog and Collection `from_dict` was causing root objects to be cached twice - once with it's ID key and once …

Fix #186 and related issues

---

docs/api.rst
docs/concepts.rst
pystac/catalog.py
pystac/item.py
pystac/layout.py
pystac/stac_object.py
tests/test_catalog.py
tests/test_item.py
tests/test_layout.py

This PR adds the `pystac.layout` module which enables STACs to layout their HREFs in several ways. Prior to this change, `normalize_href` would always generate object HREFs according to the best practices documentation - catalogs, collections and items would always have their own directory, with no additional or alternate file structure allowed.
normalize_hrefs now takes an optional `HrefLayoutStrategy` that can alter its behavior. The default keeps the existing functionality through the `BestPracticesLayoutStrategy`. Users can supply functions to modify the behavior of one or all of Catalog, Collection or Item HREFs, with a fallback to the default strategy. Additionally there is a `TemplateLayoutStrategy` which allows users to supply a template string to determine HREFs based on …

Enable normalize_hrefs to use flexible layouts.

---

pystac/catalog.py
tests/test_catalog.py

This PR adds a catalog_type as an attribute to Catalog. This is determined when reading in a catalog through inspecting the links.
Before this change, the save method on Catalog always requires a CatalogType supplied as an argument. This change determines the catalog type of a catalog that is read in by examining its Links and carries that information on the object, so that if a catalog_type is set on the catalog, it does not need to be supplied as an argument for the save call.
This is useful for users who want to read in a catalog, make a change (say, add some items), and save back the catalog, without having to think about what the original catalog type was.

Add catalog_type to Catalog to track catalog type of read STACs.

---

pystac/collection.py
tests/test_collection.py

As a follow-up to #224, set the catalog_type in Collection.to_dict
similar to how it is set in Catalog.to_dict.

Set catalog_type when reading a Collection.

---

pystac/catalog.py
pystac/item.py
tests/test_item.py

Previous to this change, using set_self_href on Item could cause assets with relative HREFs to lose a pointer to the actual asset files. This was not true in the case of using normalize_hrefs on a catalog containing the item, but calling set_self_href directly on the item could cause this problem to occur. This change moves the logic to ensure relative asset HREFs do not break when changing the Item's HREF into an overridden version of set_self_href on Item.

Modify Item set_self_href to ensure asset HREFs do not break.

---

pystac/catalog.py
pystac/collection.py
tests/test_catalog.py
tests/test_collection.py

Before this change, a cloned catalog or collection would not carry forward the catalog_type. This commit fixes this issue.

Set catalog_type on Catalog and Collection during clone

---

pystac/item.py
tests/test_item.py

This fixes a bug where a clone of item ended up with assets that did not have the owner set.

Set cloned asset owner during item clone.

---

pystac/item.py
tests/test_catalog.py
tests/test_item.py

This fixes a bug where make_asset_hrefs_relative was modifying already relative paths, which set the HREFs to invalid locations.

In Item.make_asset_hrefs_relative, leave relative hrefs alone.

---

docs/api.rst
pystac/__init__.py
pystac/extensions/sar.py
tests/extensions/test_sar.py

I'm new to type hints, so they aren't totally perfect.  The `classmethod`s are likely incorrect.  It would be great to get help to make them be correct or we can drop them. Type hints tested with pytype.
It seems like there should be a subset of `sar` available for collections.  e.g. this, which is definitely not correct.
- https://earthengine-stac.storage.googleapis.com/catalog/COPERNICUS_S1_GRD.json
- https://console.cloud.google.com/storage/browser/_details/earthengine-stac/catalog/COPERNICUS_S1_GRD.json

Implement SAR extension.  #33

---

pystac/extensions/version.py
tests/extensions/test_version.py

Prior to this change, setting the 'latest', 'successor', or 'predecessor' would add links, but not clear any old links if there were already versions set. This ensures that the links are cleared before setting any new version of the object.
It also ensures that setting a version to 'None' will clear the links, allowing users to remove a version from an item or collection.
Fixes #210

Handle setting new versions correctly in version extension.

---

docs/api.rst
pystac/__init__.py
pystac/extensions/sat.py
tests/extensions/test_sat.py

Implement SAT extension.

---

pystac/__init__.py
pystac/extensions/scientific.py
tests/extensions/test_scientific.py

https://github.com/radiantearth/stac-spec/tree/dev/extensions/scientific
This is for issue #194.  I will be tracking the changes to PR #193 to improve this extension code.

Add support for the scientific extension.

---

pystac/catalog.py
tests/test_catalog.py

Fix unexpected behaviour of `generate_subcatalogs`

---

pystac/extensions/eo.py
tests/extensions/test_eo.py

**Context**
As defined in the [EO extension](https://github.com/radiantearth/stac-spec/tree/master/extensions/eo) specification, the `eo:bands` properties are allowed in assets without being declared at the item level
**Issue**
The `get_bands` method in `EOItemExt` does not return bands defined in asset level if no `asset` parameter in specified.
**Proposed Solution**
The `get_bands` method in `EOItemExt` return aggregated list of bands defined in asset level if no `asset` parameter in specified.

Get eo bands defined in assets only

---

docs/concepts.rst
pystac/catalog.py
pystac/validation/stac_validator.py
requirements-dev.txt
scripts/format
tests/test_writing.py

Previously only link href types (absolute vs relative) were modified as part of the `Catalog.save` process based on the catalog types: for ABSOLUTE_PUBLISHED, all link hrefs were made absolute, etc. The asset HREFs were not modified, which was counter to the expected result outlined in stac-utils/stactools#31.
This change causes asset HREFs to also be changed to absolute or relative based on the catalog type. Note that if the asset HREF cannot be made relative, e.g. the asset HREF points to an HTTP location and the item is being stored locally, then the HREF is left unchanged.
Also upgrade yapf to 0.30.* and add a `scripts/format` script to run code formatting.

Make asset HREFs relative or absolute based on CatalogType during save

---

CHANGELOG.md
pystac/extensions/view.py
tests/extensions/test_view.py

Resolves https://github.com/stac-utils/pystac/issues/258, in which parameters that were not passed to the `.apply()` method in the view extension would result in validation issues. 
Updated:
- Only sets property is passed is not None
- Raise error if all parameters are None
- Added tests for added functionality

handle optional arguments in View Extension

---

CHANGELOG.md
pystac/catalog.py
pystac/extensions/__init__.py
pystac/extensions/label.py
pystac/link.py
pystac/media_type.py
pystac/stac_object.py

For https://github.com/stac-utils/pystac/issues/231. I'm guessing you only need the `__str__` override for the `MediaType` class, since that's the only one that's likely to actually get printed?

Subclass relevant classes from Enum

---

CHANGELOG.md
pystac/extensions/projection.py
tests/extensions/test_projection.py

Before this change, setting a projection extension value to None would break if the value wasn't required; the proper way to handle this case is to pop the property key or not set it. This fixes an issue brought up in #268 around using apply with the only required property (epsg).
Fixes #268

Fix issue with projection extension setters handling None values.

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
pystac/item.py
pystac/link.py

Calls to `deepcopy` are fairly expensive when working with large number of STACs. In `to_dict` methods, a dictionary `d` is instantiated only to have `deepcopy` applied to it for the `return` value. This seems to be unnecessary.
Here's `snakeviz` output of some `cProfile` timings.
Before:
After:
It should be noted that the after includes also the use of `orjson` to optimize ser/de operations. This optimization can be left out of `pystac` because it requires an external dependency and because it can easily be plugged in through a `STAC_IO` subclass

Remove unnecessary deepcopies

---

pystac/extensions/base.py
pystac/extensions/eo.py
pystac/extensions/pointcloud.py
pystac/extensions/projection.py
pystac/extensions/timestamps.py
pystac/extensions/view.py
tests/extensions/test_timestamps.py

This PR adds a method to the ItemExtension class, that makes it easier and more robust for derived classes to set properties in Assest and/or Items. 
Existing extensions needing that mechanism have been refactored to rely on the parent method instead
This was discussed in https://github.com/stac-utils/pystac/pull/270
If this PR is merged, https://github.com/stac-utils/pystac/pull/230 will be no longer needed

Extract method to correctly handle setting properties in Item/Asset for ItemExtensions

---

.codespellignore
pystac/__init__.py
pystac/extensions/__init__.py
pystac/extensions/file.py
tests/data-files/file/file-example.json
tests/extensions/test_file.py

It adds support for data_type, nodata, checksum and size
The tests only cover the support for values in assets, since I am not sure how to apply (or even if it makes sense to ) those parameters can be applied outside of the asset level...

added support for STAC file extension

---

CHANGELOG.md
pystac/extensions/pointcloud.py
tests/data-files/pointcloud/example-laz-no-statistics.json
tests/extensions/test_pointcloud.py

stac-utils/stactools#44
The `statistics` attribute of the pointcloud extension is optional, but `PointcloudItemExt.get_statistics` was erroring if the pointcloud was missing stats. This fixes the issue to return `None` if there are no statistics defined.

Don't error when pointcloud statistics are missing

---

CHANGELOG.md
pystac/item.py
tests/test_item.py

Currently if you call `set_self_href` on an Item with `None` as the parameter, if that item has assets with relative hrefs, the logic that attempts to ensure relative asset hrefs remain valid when switching the item href ends up throwing an error. This change makes it so that, if you are setting the item self href to None, any relative asset hrefs are left as is.

Don't fail on item.set_self_href(None) for items with relative asset hrefs

---

CHANGELOG.md
docs/concepts.rst
docs/tutorials/adding-new-and-custom-extensions.ipynb
pystac/__init__.py
pystac/catalog.py
pystac/extensions/base.py
pystac/item.py
pystac/link.py
pystac/stac_object.py
tests/data-files/collections/multi-extent.json
tests/data-files/eo/eo-landsat-example.json
tests/data-files/eo/sample-bands-in-item-properties.json
tests/data-files/file/file-example.json
tests/data-files/label/label-example-1.json
tests/data-files/label/label-example-2.json
tests/test_catalog.py
tests/test_link.py
tests/test_writing.py

#286 , also resolves #285
This PR removes the link_type field and the LinkType class, along with the need to loop through all links to set them as RELATIVE or ABSOLUTE.
Instead, when a link href is requested it returns an absolute link unless all the following are true:
- The link is a hierarchical link ('root', 'child', 'parent', 'item')
- The link has an owner (i.e., it is part of a STAC object and not a standalong Link instance)
- The owner has a root catalog
- The root catalog.catalog_type is CatalogType.RELATIVE_PUBLISHED
When all are true the link relative to the owner is returned.
There are some additional implications and related changes:
- Catalog.catalog_type is now always defined, never None. It defaults to ABSOLUTE_PUBLISHED
- A user …

Remove link type

---

CHANGELOG.md
pystac/catalog.py

#284 
When an existing catalog and an item or child is added to it, the self_href was not set which meant that they had to either be set manually, or a call to `normalize_hrefs` would be needed. This would also happen if `generate_subcatalogs` was used....all the subcatalogs and items added will need to be normalized.
However, since the catalog already exists, this should be unnecessary. Given a layout strategy, a self href can be determined and set, if the parent has a self href.
*Note the only case where a parent does not have a self href is when the catalog is first created in memory and has not yet been saved. In that case a call to `normalize` is needed*

Set self href on items and children when adding

---

pystac/catalog.py

The Catalog.generate_subcatalogs function was taking a long time with large catalogs (> several thousand items). Profiling revealed that the `Catalog.remove_item` was a significant factor. `remove_item` performs some redundant tasks, and is really not necessary. Instead of removing the item from the original location, when all item links have been moved, those links are removed from the STAC object.
A ~4000 item catalog takes 3 seconds vs 30 seconds to generate the subcatalogs after this change. A 25K item catalog takes about 3 minutes.

faster generate_subcatalogs

---

pystac/catalog.py
pystac/serialization/identify.py

https://github.com/radiantearth/stac-spec/pull/971
Adds tpe property for catalogs and collections

added type property for catalogs and collections

---

CHANGELOG.md
tests/extensions/test_pointcloud.py
tests/extensions/test_projection.py

**Related Issue(s):** #339
**Description:** There were a few instances in the test suite where we wanted to validate an item, but the method wasn't actually called.

Execute the validate method in tests

---

.github/workflows/continuous-integration.yml
.style.yapf
CHANGELOG.md
pystac/stac_io.py
scripts/format
tests/test_stac_io.py

**Description:** If orjson was not present, the `_json_loads` method on `StacIO` would try to read the text again, which would lead to the read text method being called with json (bad). This slipped through CI because one of the requirements-dev.txt dependencies installs orjson, so the non-orjson case wasn't being tested. This commit also includes a new build job to install+test without requirements-dev.txt to try and protect against regression.
Also includes a scripts comment fix to s/yapf/black, and a comment to make pylance ignore a missing orjson import. I didn't update the docs re the yapf->black switch b/c @lossyrob said that some other folks were working on the docs upgrades.

Remove duplicate `read_text` without orjson

---

CHANGELOG.md
pystac/stac_io.py

**Related Issue(s):** https://github.com/stac-utils/stactools/pull/113
**Description:** This allows subclasses of `DefaultStacIO` to not have to re-impelment link resolution if they don't want to. I would like this for, e.g., [this fsspec io](https://github.com/stac-utils/stactools/pull/113/files#diff-3d671a54c5fbbcedc1f768fb8e61ee8c36d16f46f8e9c69798a32b966a4bdcc4R25-R49), where right now I'm just copying the link resolution code from pystac.

Split default IO down into to/from href methods

---

CHANGELOG.md
tests/extensions/test_pointcloud.py

**Related Issue(s):** #248 
**Description:** Increase coverage for pointcloud extension tests. Doesn't go 100% b/c I don't like testing `__repr__` and there's some property getter paths that don't seem worth exploring because they seem like they're already protected in one of the superclasses.

Add more pointcloud extension tests

---

docs/api.rst
docs/concepts.rst
docs/conf.py
pystac/extensions/base.py
pystac/extensions/eo.py
pystac/stac_object.py
tests/extensions/test_eo.py

#326 
#353 
* Adds docstrings for the extension base classes
* Updates docstrings for the new EO extension classes
* Updates the "Extensions" section of the "Concepts" docs to reflect the new extension structure
* Other fixes to the docs to make the above changes work
I plan on submitting 1-2 more PRs to address the remaining extension documentation work for #326, but I wanted to get feedback on this first since I'll likely use it as a template for the other extensions.

Update EO extension docs

---

CHANGELOG.md
pystac/extensions/eo.py
tests/data-files/eo/eo-landsat-example.json
tests/extensions/test_eo.py

**Related Issue(s):** #356
added solar_illumination field accessor in `eo` extension

Add solar_illumination field in eo extension

---

.coveragerc
scripts/test

**Related Issue(s):** https://github.com/stac-utils/pystac/issues/331
**Description:** Enforce the current level of code coverage, to make it easy to detect any substantial reduction and to bump it when coverage increases.

Enforce coverage percentage

---

pystac/extensions/eo.py

Trivial addition of typing to module level strings

eo.py: Add more typing info for module level strings

---

CHANGELOG.md
doc8.ini
docs/api.rst
docs/concepts.rst
docs/conf.py
docs/contributing.rst
docs/index.rst
docs/tutorials.rst
pystac/catalog.py
pystac/extensions/label.py
pystac/layout.py
pystac/stac_object.py
requirements-dev.txt
scripts/test

* Fixes GitHub username in `docs/conf.py`
* Uses the `:stac-spec:` extlink for all links to the STAC spec. This will automatically generate links to the version of the spec from `pystac.version.STACVersion.DEFAULT_STAC_VERSION` (there were a number of these links that were still pointing to old spec versions).
* Uses the `:stac-ext:` extlink for all links to STAC Extensions specs.
* Updates RST files to have a max line length of 88 to match linting on other files
* Uses [`doc8`](https://github.com/pycqa/doc8) to lint all source files for the docs (except tutorials) as part of `./scripts/test`
If this last one seems too heavy-handed I'm happy to remove it, but I thought it would help keep us from getting some of the really long lines that had snuck in before.
**PR …

Fix spec links and shorten line lengths

---

README.md

* Fixes Codecov badge to point to `main` branch instead of `develop`

Point coverage badge to main branch

---

tests/extensions/test_eo.py
tests/extensions/test_file.py
tests/extensions/test_label.py
tests/extensions/test_pointcloud.py
tests/extensions/test_projection.py
tests/extensions/test_raster.py
tests/extensions/test_timestamps.py
tests/extensions/test_view.py
tests/test_item.py
tests/utils/__init__.py

Fixes #387 
Modifies `def test_to_from_dict` in `tests/utils/__init__.py` to `def assert_to_from_dict` to avoid conflict with other test runners

Handle `tests.utils.test_to_from_dict` conflict with other test runners

---

pystac/extensions/datacube.py

Also sets AssetDatacubeExtension.additional_read_properties to None if it won't have a value.

datacube.py: Additional class member typing

---

mypy.ini
pystac/__init__.py
pystac/catalog.py
pystac/extensions/base.py
pystac/extensions/label.py
pystac/extensions/pointcloud.py
pystac/item.py
pystac/serialization/__init__.py
pystac/serialization/common_properties.py
pystac/serialization/identify.py
pystac/stac_io.py
pystac/stac_object.py
pystac/summaries.py
pystac/utils.py
pystac/validation/__init__.py
pystac/validation/stac_validator.py
tests/serialization/test_identify.py
tests/test_item.py
tests/utils/__init__.py

**Related Issue(s):** #332
**Description:** Applies stricter mypy configuration to the code base

Improve mypy strictness

---

.github/dependabot.yml

**Related Issue(s):** N/A
**Description:** Tell Dependabot to automatically generate pull requests to change the requirements file when updated Python packages are available. This should allow the project to easily keep up with package updates.
[Example PR](https://github.com/linz/geostore/pull/753) created by Dependabot. As you can see, it includes some excellent information, including previous and new version number, release notes, change log, and commits involved in the upstream change.

feat: Upgrade Python packages automatically

---

CHANGELOG.md
pystac/extensions/eo.py
tests/data-files/eo/eo-sentinel2-item.json
tests/extensions/test_eo.py

**Related Issue(s):** #404
- fix `get_bands` in `AssetEOExtension` to return None if no `eo:bands` property for the asset
- test to reproduce #404 case

Fix get_bands in AssetEOExtension to return None if no eo:bands property for the asset

---

CHANGELOG.md
docs/conf.py
setup.py

* #403 
* Updates author info
* Adds project URLs for documentation, Issues page, and GitHub Discussions page. All of these will show up as links in PyPi.
* Includes LICENSE file in package distribution
* Sets minimum Python version at `>=3.6`

Update package metadata

---

.gitignore

* Adds a more thorough `.gitignore` file to cover common files/directories for Python development
@l0b0 Thanks for the push on this in [this comment](https://github.com/stac-utils/pystac/pull/337#discussion_r639220845). I'm curious if anyone else has a different opinion on this.

More thorough gitignore

---

requirements-dev.txt
requirements-test.txt

* Bumps versions of `black`, `codespell`, `nbsphinx`, `jinja2`
Bumping `nbpshinx` to `0.8.6` fixes spatialaudio/nbsphinx#563, which was the reason we had pinned `jinja2` to `<3.0` in the first place.
* Drops `pylint` and `sphinx-autobuild`
`pylint` seemed like it was added as a dependency early on, but isn't actually used anymore. `sphinx-autobuild` is not used in our tests, linting, or doc builds, so it seems more appropriate for individual developers to install it themselves if it's part of their personal workflow.
Supersedes #423, #421, #415, #414, and #413
**UPDATE 2021-06-10:**
* Bumps versions of `ipython`, `flake8`
* Also supersedes #428, #427, and #426
**UPDATE 2021-06-11**
* Bumps `mypy` and `codespell` again
* Also supersedes #436 and #435

Update dev dependencies

---

CHANGELOG.md
pystac/stac_io.py

* Closes #411 
Adds `*args` and `**kwargs` parameters to `StacIO.read_json` and passes them to `StacIO.read_text`.

Add args/kwargs to StacIO.read_json

---

CHANGELOG.md
docs/api.rst
docs/conf.py
pystac/__init__.py
pystac/item_collection.py
pystac/serialization/__init__.py
pystac/serialization/identify.py
pystac/serialization/migrate.py
pystac/stac_object.py
pystac/validation/schema_uri_map.py
tests/data-files/change_stac_version.py
tests/data-files/item-collection/sample-item-collection.json
tests/extensions/test_eo.py
tests/extensions/test_pointcloud.py
tests/extensions/test_raster.py
tests/extensions/test_timestamps.py
tests/serialization/test_identify.py
tests/serialization/test_migrate.py
tests/test_collection.py
tests/test_item_collection.py
tests/test_stac_io.py
tests/validation/test_validate.py

* #371 
Adds `ItemCollection` class to work with GeoJSON Feature Collections containing only STAC Items. This class can be serialized/deserialized from JSON, and also implements [`Collection`](https://docs.python.org/3/library/typing.html#typing.Collection) to make it more convenient to loop over items, get an item by index, and check if an Item is included. Note that until we implement more specific STAC object equality (as per #380), `assert item in item_collection` will always fail unless `clone_items=False` is used when instantiating the `ItemCollection`.
This PR also updates the I/O functions in `pystac.__init__` to work with the new `ItemCollection` class in response to #371. Since `ItemCollection`s are not `STACObject`s, this means that the …

Add basic ItemCollection implementation

---

.github/workflows/continuous-integration.yml
CHANGELOG.md
setup.py

Expands CI test matrix to include Python 3.9 and 3.10. Python 3.10 is marked as "experimental", so the CI workflow will still succeed even if that job fails.

Test against Python 3.9

---

.github/workflows/continuous-integration.yml
.gitignore
tests/data-files/get_examples.py
tests/extensions/test_label.py
tests/test_catalog.py
tests/test_collection.py
tests/test_item.py
tests/test_stac_io.py
tests/test_writing.py
tests/utils/__init__.py
tests/validation/test_validate.py

* Closes #418
Uses `TMPDIR` environment variable to change temporary directory location in Windows builds instead of hard-coding the CWD.

Use environment variable for tmp dir location

---

.coveragerc
CHANGELOG.md
docs/api.rst
pystac/extensions/eo.py
pystac/extensions/file.py
pystac/extensions/label.py
pystac/extensions/version.py
tests/data-files/file/collection.json
tests/data-files/file/item.json
tests/extensions/test_file.py
tests/extensions/test_label.py

* #331 
* #326
* Updates docstrings to be consistent with other extensions
* Updates implementation to be consistent with v2.0.0 of the extension spec
* Makes `FileExtension` a concrete class on Assets since the spec only defines properties on Assets
* Updates docstrings to be consistent with other extensions
* Adds tests to bring coverage up to 95%
* Updates docstrings to be consistent with other extensions
* Adds tests to improve coverage to 95%
* Brings code style in line with other extensions
Added constants for all property names, changed the bodies of many of the property methods to rely on type checking for input validation, and used `get_required` and `get_opt` more consistently.
* Bumps minimum allowed coverage to 90% since this PR brings it over that threshold.

Update docs and tests for Version, Label, and File Info extensions

---

CHANGELOG.md
docs/api.rst
pystac/stac_io.py
tests/test_stac_io.py

* #431
Moved this out of #443 so we can integrate it separately. Also added a Deprecated section to the 1.0.0-beta.1 CHANGELOG section so that the deprecation is more obvious there.

More specific STAC_IO deprecation warnings

---

CHANGELOG.md
pystac/serialization/migrate.py
tests/serialization/test_migrate.py
tests/test_collection.py

Add migration for pre-1.0.0-rc.1 Stats Object

---

CHANGELOG.md
pystac/extensions/base.py
tests/extensions/test_eo.py

* Closes #369 
`pystac.extensions.base.ExtensionManagementMixin.add_to` will only add the schema URI for the inheriting extension class if it is not already in the object's `stac_extensions` list. 
I looked into making `stac_extensions` a `set` instead of a `list`, but the extra complexity to ensure that the set was properly serialized and deserialized did not seem worth the effort. If that seems like the better approach, I can explore it in more depth, though.

Make ExtensionManagementMixin.add_to idempotent

---

.github/pull_request_template.md
.github/workflows/continuous-integration.yml
.github/workflows/release.yml
README.md

* Removes Gitter badge since that channel is mostly unused
* Adds `orjson` extra install instructions
* Minor clarifications around versions
* Only run release build for this repo (I was seeing failed builds in my fork when I updated tags)
* Move coverage reporting into separate job
Since we added the minimum coverage requirement, the `test` job fails before uploading coverage to Codecov.io. When I was working on removing support for pre-0.8 STAC versions I found myself wishing I could use that UI to figure out where the coverage had dropped. This change means the CI workflow will still fail overall, but we will still get a coverage report we can look at if we drop below the minimum threshhold.

Updates to CI and README

---

pystac/__init__.py
pystac/catalog.py
pystac/collection.py
pystac/item.py
pystac/serialization/__init__.py
pystac/stac_io.py
pystac/stac_object.py
tests/test_catalog.py
tests/test_collection.py
tests/test_item.py
tests/test_stac_io.py
tests/test_writing.py

* #410 
Updates `from_dict` and `from_file` methods for `STACObject` and all sub-classes so that any classes inheriting from them will be returned by those methods. This makes it easier for downstream libraries like pystac-client to create custom sub-classes. See [these tests](https://github.com/duckontheweb/pystac/blob/6e0785b45960c178c7b73039220589ac6f4723ac/tests/test_catalog.py#L1112-L1133) for an example.
Also moves the logic from `serialization.stac_object_from_dict` into `stac_io` to simplify the chain of functions that is called. If it seems like downstream libraries are using this function directly we can go through a deprecation process, but it seemed unlikely. Once `STAC_IO` is removed in 1.0.0 this code will only be used in one place in …

Fix STACObject inheritance

---

pystac/catalog.py
pystac/collection.py
pystac/item.py
pystac/stac_io.py
pystac/stac_object.py
tests/test_catalog.py
tests/test_collection.py
tests/test_item.py

**Related Issue(s):** #453 
This PR adds a parameter to the `STACObject.from_dict` method and implementations named `preserve_dict`. If this is True, the dict that is passed in as a parameter will not be mutated during the operation - which is achieved by making a deep copy of dict parameter in the implementing methods. If preserve_dict is False, the incoming dict is mutated and a deepcopy is avoided. The default of this parameter is True, so that users can avoid a situation where their parameters are mutated unsuspectedly. In situations where the dict is a transient encoding of the STAC object, users should use preserve_dict=False to avoid incurring the performance cost of the deepcopy.
`preserve_dict` is set to False for methods that read a STAC object from a file, as …

Avoid calling deepcopy in from_dict methods when unnecessary

---

CHANGELOG.md
pystac/version.py

Version 1.0.0-rc.1

---

.github/workflows/continuous-integration.yml
.github/workflows/release.yml

* Updates the CI to upload coverage to Codecov.io on pushes to the release branches. This fixes an issue where the coverage report for PRs against those branches found no base coverage to compare against.
* Fixes GitHub repo check in `release` workflow
* Publishes to PyPi on release creation instead of tag push

Upload coverage for release branches

---

CHANGELOG.md
pystac/item_collection.py
tests/test_collection.py
tests/test_item_collection.py

**Related Issue(s):** #453
When I made #454, I wasn't hip to the fact the ItemCollection got merged in already. This PR adds the `preserve_dict` parameter to ItemCollection.from_dict and uses preserve_dict=False when using `ItemCollection.from_file`.

Add preserve_dict parameter to ItemCollection.from_dict

---

CHANGELOG.md
docs/api.rst
docs/concepts.rst
pystac/__init__.py
pystac/errors.py
pystac/stac_io.py
tests/test_stac_io.py

* Closes #467 
* Closes #432 
* #313 
* Makes "private"  `StacIO._json_dumps` method  into a "public" `StacIO.json_dumps` and updates the signature to accept arbitrary keyword arguments instead of specifically accepting a `source` argument (see #467).
* Refactors error reporting logic for `DuplicateKeyReportingMixin.read_json` and `DuplicateKeyReportingMixin.json_loads` so that we do not need to pass the `source` into `json_loads`. Also adds test coverage for this class.
* Adds all exception classes to API docs
* Moves `DuplicateObjectKeyError` into `pystac.errors`
* Updates the API docs for the `stac_io` classes as well as the "Using STAC_IO" section in the "Concepts" docs

Updates to StacIO

---

CHANGELOG.md
pystac/version.py

Set the version to 1.0.0-rc.2 and update the CHANGELOG in preparation for release

PySTAC version 1.0.0-rc.2

---

.coveragerc

Missing coverage in tests means unreached (and usually unreachable) test
code, often indicating a test bug.

tests: Include tests in coverage metric

---

tests/test_catalog.py
tests/test_item_collection.py
tests/test_utils.py

By using the current file rather than the root of the project as the
reference, the tests are now runnable for example in an IDE which uses
the "tests" directory as the root.

tests: Make tests runnable from anywhere

---

.coveragerc

tests: Exclude mypy-specific code from coverage

---

docs/api.rst
pystac/__init__.py
pystac/collection.py
tests/test_collection.py
tests/test_item.py

* #479
* Handles additional top-level fields in `Provider`, `Extent`, `SpatialExtent`, and `TemporalExtent` classes. These additional fields are stored in an `extra_fields` dict on the instance. 
* Uses `SpatialExtent.clone` and `TemporalExtent.clone` in `Extent.clone` instead of using `copy`
* Adds `ProviderRole` enum for use in the Provider `"roles"` attribute
* Removes support for pre-0.8 extents

Allow extra fields in Provider and Extent 

---

.github/workflows/continuous-integration.yml
CHANGELOG.md
README.md

* #331 
Adds Python 3.10 to the test matrix, but allows the CI workflow to succeed even if any Python 3.10 job fails. The main hiccup is that `orjson` does not have Python 3.10 wheels for Windows or MacOS, and needs the Rust nightly toolchain to build. The CI job installs Rust nightly for Python 3.10 jobs, and this PR adds a note in the Installation docs describing this requirements.

Experimental Python 3.10 support

---

pystac/extensions/sar.py
pystac/extensions/view.py
tests/extensions/test_sar.py
tests/extensions/test_view.py

Verify empty observation direction property

---

.github/workflows/continuous-integration.yml
docs/contributing.rst
scripts/test

* #466 (specifically [this comment](https://github.com/stac-utils/pystac/pull/466#issuecomment-868982522))
Adds ability to run `scripts/test` with or without coverage (default outside of CI is still to run with coverage). 
Also moves generation of `coverage.xml` out of `scripts/test`. The XML file is mostly used when uploading coverage to Codecov.io. Generating this file would cause all `test` jobs in the matrix to fail if the coverage dropped, which is misleading. Instead, this PR updates the `coverage` CI job to first upload the coverage report to Codecov.io so we can use it for debugging, then generates the report again using the configured `fail-under` value, which will cause `coverage` job to fail if coverage drops. This should make the source …

Run test script with/without coverage

---

CHANGELOG.md
pystac/extensions/label.py
tests/data-files/label/spacenet-roads/roads_collection.json
tests/extensions/test_label.py

* #327
* Defines equality for component classes in the Label Extension (e.g. `LabelClasses`, `LabelProperties`, etc.)
* Adds summaries for fields defined in `stac-fields`
* Uses `Enum` for `"label:tasks"`, but continues to allow free string input (following pattern for `RelType`).

Add Label Extension summaries

---

.coveragerc

tests: Bump coverage minimum to 95%

---

pystac/extensions/datacube.py
pystac/extensions/eo.py
pystac/extensions/file.py
pystac/extensions/item_assets.py
pystac/extensions/label.py
pystac/extensions/pointcloud.py
pystac/extensions/projection.py
pystac/extensions/raster.py
pystac/extensions/sat.py
pystac/extensions/scientific.py
pystac/extensions/timestamps.py
pystac/extensions/version.py
tests/extensions/test_custom.py
tests/extensions/test_datacube.py
tests/extensions/test_eo.py
tests/extensions/test_file.py
tests/extensions/test_label.py
tests/extensions/test_pointcloud.py
tests/extensions/test_projection.py
tests/extensions/test_raster.py
tests/extensions/test_sat.py
tests/extensions/test_scientific.py
tests/extensions/test_timestamps.py
tests/extensions/test_version.py
tests/serialization/test_migrate.py

Based on <https://stackoverflow.com/a/13477954/96588>.
Also add tests to verify the exception being thrown.

feat: Print human readable type name in error messages

---

.coveragerc
tests/extensions/test_sar.py
tests/extensions/test_scientific.py
tests/extensions/test_version.py
tests/serialization/test_identify.py
tests/test_version.py
tests/test_writing.py
tests/validation/test_validate.py

Increase test coverage

---

.coveragerc

Stricter than statement coverage, so I had to take the coverage minimum
down one percentage point.
The coverage library does not yet have support for conditional coverage
<https://github.com/nedbat/coveragepy/issues/660>, which is even
stricter.
Hover over yellow lines in the output of `coverage html` for a good idea of the difference between this and line coverage.

tests: Verify branch coverage

---

tests/test_item.py

`Catalog.get_all_items` is contracted to return `Iterable[Item]`, so we
shouldn't have to filter the response.
**Related Issue(s):** #331 

tests: Trust method signature to be accurate

---

tests/utils/__init__.py

chore: Remove unused import

---

CHANGELOG.md
docs/api.rst
pystac/extensions/eo.py
pystac/extensions/timestamps.py
pystac/summaries.py
tests/extensions/test_timestamps.py
tests/test_summaries.py

* #326
* #327
* Update docstring and adds Summaries for Timestamps Extension
* Defines equality and `__repr__` for `RangeSummary` (cherry picked from #509, so there should be no conflict)

Update Timestamps Extension

---

CHANGELOG.md
pystac/asset.py
pystac/catalog.py
pystac/collection.py
pystac/item.py
pystac/link.py
tests/test_catalog.py
tests/test_collection.py
tests/test_item.py
tests/test_link.py

Following in the footsteps of #451, this changes the Link constructor methods (`Link.from_dict`, etc.) to return the calling class instead of hard-coding the `Link` class as the return type. This allows downstream libraries and users to sub-class `Link` and still be able to use these constructors.
**UPDATE:** Also does the same for `Asset` constructors and for `clone` methods on `Catalog`, `Collection`, `Item`, `Link`, and `Asset` classes.

Return calling class from Link constructor methods

---

CHANGELOG.md
pystac/asset.py
pystac/extensions/datacube.py
pystac/extensions/eo.py
pystac/extensions/file.py
pystac/extensions/item_assets.py
pystac/extensions/label.py
pystac/extensions/pointcloud.py
pystac/extensions/projection.py
pystac/extensions/raster.py
pystac/extensions/sar.py
pystac/extensions/sat.py
pystac/extensions/timestamps.py
pystac/extensions/view.py
pystac/item.py
pystac/link.py
tests/extensions/test_custom.py
tests/extensions/test_eo.py
tests/extensions/test_pointcloud.py
tests/extensions/test_raster.py
tests/test_item.py
tests/test_link.py

* #479 (see [this comment](https://github.com/stac-utils/pystac/issues/479#issuecomment-869968926))
* #321
Adds type annotations for `Link` and `Asset` attributes and uses these in API documentation. Changes `properties` to `extra_fields` for `Link` and `Asset` classes to use more consistent naming across PySTAC classes. 

`properties` -> `extra_fields` for Asset and Link

---

CHANGELOG.md
docs/api.rst
pystac/extensions/sat.py
tests/extensions/test_sat.py

* Closes #507
* #326
* #327
* Adds missing fields to Satellite Extension
* Implements collection summaries for Satellite Extension
* Defines `__eq__` and `__repr__` for `RangeSummary`
I found myself wanting to use this when testing summaries
Let me know what you think about the implementation of the RangeSummary for the `sat:anx_datetime` field, which has a  `datetime` type.

Update Satellite Extension

---

CHANGELOG.md
pystac/catalog.py
pystac/stac_object.py
tests/test_catalog.py

* Closes #169
- Adds `Catalog.get_collections` method to return all child `Collection` instances from a `Catalog`
- Adds `Catalog.get_all_children` method to recursively return all child `Collection` instances form a `Catalog` and its children

Add get_collections + get_all_collections methods to Catalog

---

.flake8
pystac/__init__.py
pystac/serialization/__init__.py
pystac/validation/__init__.py
tests/utils/__init__.py

By only ignoring error 401 ("imported but unused") we can lint these
files for any other issues.

refactor: Reintroduce linting to `__init__` files

---

.github/workflows/continuous-integration.yml
CHANGELOG.md
README.md
setup.py

* Closes #474
Drops support for Python 3.6 (both in terms of `python_version` check on install and in CI tests), and adds a note to the README that we follow the NEP-29 guidelines.

RFC: Drop support for Python 3.6

---

pystac/extensions/datacube.py
pystac/extensions/eo.py
pystac/extensions/file.py
pystac/extensions/item_assets.py
pystac/extensions/label.py
pystac/extensions/pointcloud.py
pystac/extensions/projection.py
pystac/extensions/sar.py
pystac/extensions/sat.py
pystac/extensions/scientific.py
pystac/extensions/timestamps.py
pystac/extensions/version.py
pystac/extensions/view.py
pystac/stac_object.py

Also removed their type annotations since they were inferred by mypy.

refactor: Change some `set()` calls into literals

---

mypy.ini

**Related Issue(s):** #332 
**Description:** This is almost as strict as `strict = True`, which can replace every strictness setting already in place once we fulfill `no_implicit_reexport = True`, which I'll try to do in a separate PR since we need to resolve import cycles to do it.

refactor: Use stricter mypy configuration

---

pystac/catalog.py
pystac/extensions/eo.py
pystac/extensions/projection.py
pystac/extensions/raster.py
pystac/serialization/migrate.py
tests/utils/test_cases.py

Gets rid of most of the flake8 exclude comments.

refactor: Split long lines

---

pystac/catalog.py
pystac/collection.py
pystac/extensions/file.py
pystac/extensions/label.py
pystac/extensions/raster.py
pystac/extensions/scientific.py
pystac/extensions/version.py
pystac/media_type.py
pystac/rel_type.py
pystac/stac_object.py
pystac/utils.py
tests/extensions/test_file.py
tests/extensions/test_label.py
tests/extensions/test_version.py

They were only accessed by tests.
**Related Issue(s):** #505

chore: Remove unused `__str__` methods

---

CHANGELOG.md
pystac/version.py

Update version and CHANGELOG for v1.0.0-rc.3 release.

Release v1.0.0-rc.3

---

pystac/catalog.py
pystac/extensions/base.py
pystac/extensions/label.py
pystac/serialization/common_properties.py
pystac/validation/schema_uri_map.py

chore: Remove unused locals

---

CHANGELOG.md
pystac/extensions/projection.py
tests/extensions/test_projection.py

**Description:** This can be used to feed, e.g. rasterio's CRS.from_string without having to worry about which projection field is set.

Add `ProjectionExtension.crs_string`

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
pystac/item.py
pystac/item_collection.py
pystac/stac_object.py
tests/test_catalog.py
tests/test_collection.py
tests/test_item.py
tests/test_item_collection.py

**Related Issue(s):** #546
There was existing unused arguments for setting the root on from_dict for Catalogs, Collections and Items. This commit implements and tests that the root is set to the parameter if present, and adds the parameter to ItemCollection, which itself does not have a root but instead passes the root onto each of the Items parsed during the from_dict call.
This will allow pystac_client to pass in the client Catalog as the root of the Items returned during a search. This will drastically speed up the `item.to_dict()` calls as the logic in to_dict checks the root to see if the HREFs should be absolute or relative, which ends up reading the root object for each Item in the search results; instead if the root is set at the time of `item.from_dict`, the …

Allow root to be set during to_dict

---

CHANGELOG.md
pystac/extensions/eo.py
pystac/extensions/label.py
pystac/extensions/projection.py
pystac/extensions/raster.py
pystac/extensions/sat.py
pystac/extensions/scientific.py
pystac/extensions/timestamps.py
pystac/extensions/view.py
tests/extensions/test_eo.py
tests/extensions/test_label.py
tests/extensions/test_projection.py
tests/extensions/test_raster.py
tests/extensions/test_sat.py
tests/extensions/test_scientific.py
tests/extensions/test_timestamps.py
tests/extensions/test_view.py

**Related Issue(s):** #525 
**Description:** This PR adds `pystac.Collection` to the `ExtensionManagementMixin` type params (via a `Union`) for all extensions that provide concrete implementations of `SummariesExtension`.
- ~Documentation has been updated to reflect changes, if applicable~

Add collection to ExtensionManagementMixin type params where appropriate

---

.readthedocs.yaml
requirements-dev.txt
requirements-docs.txt

* #552
This temporarily disables building the PDF docs until the underlying issue with `nbsphinx` is resolved. Also moves our docs dependencies into a separate file and uses a `.readthedocs.yaml` file for configuration.

Fix docs build, add config

---

CHANGELOG.md
docs/api.rst
pystac/extensions/eo.py
pystac/extensions/sar.py
tests/extensions/test_sar.py

- #326
- #327
- #262
- Updates docstrings for SAR Extension implementation
- Adds Collection summaries for SAR Extension
- Adds migration for pre-0.9 SAR fields:
- `sar:type` -> `sar:product_type`
- `sar:polarization` -> `sar:polarizations`

Update SAR Extension

---

pystac/stac_io.py

Since `orjson.dumps` and `json.dumps` don't support the same options, we
probably don't want to forward arbitrary arguments to them in any case.

chore: Remove unused parameters recursively

---

CHANGELOG.md
docs/api.rst
pystac/extensions/pointcloud.py
tests/extensions/test_pointcloud.py

- #326
- #327
I've intentionally left #518 for a separate PR that includes all extension name changes.
- Updates docstrings and adds Collection summaries for Point Cloud Extension

Update Point Cloud Extension

---

CHANGELOG.md
pystac/extensions/eo.py
tests/extensions/test_eo.py

- #262
Adds migration for `eo:epsg` to `proj:epsg` for pre-0.9 catalogs.

Add migration for eo:epsg to proj:epsg

---

CHANGELOG.md
pystac/extensions/base.py
pystac/extensions/datacube.py
pystac/extensions/eo.py
pystac/extensions/file.py
pystac/extensions/item_assets.py
pystac/extensions/label.py
pystac/extensions/pointcloud.py
pystac/extensions/projection.py
pystac/extensions/raster.py
pystac/extensions/sar.py
pystac/extensions/sat.py
pystac/extensions/scientific.py
pystac/extensions/timestamps.py
pystac/extensions/version.py
pystac/extensions/view.py
tests/extensions/test_eo.py

* #521
Raises an `STACError` if `add_if_missing` is `True` for an `Asset` with no `owner`. 
This PR also moves the `add_if_missing` logic into `ExtensionManagementMixin.validate_has_extension` for DRYer code in the extension implementations.

Raise exception when using add_if_missing on ownerless Asset

---

CHANGELOG.md
pystac/link.py
pystac/stac_object.py
tests/test_link.py

**Related Issue(s):** #499.
**Description:** When getting a STAC object's self href, there was a cast that assumed that the object's self link's target was a string, which was not always the case (the self link's target could be a string or another STAC object). This commit removes that cast by splitting a link's target into two separate "private" attributes, `_target_href` and `_target_object`.

Allow resolved self links

---

CHANGELOG.md
pystac/extensions/datacube.py
pystac/extensions/eo.py
pystac/extensions/file.py
pystac/extensions/pointcloud.py
pystac/extensions/raster.py
pystac/extensions/sar.py
tests/extensions/test_pointcloud.py

- Closes #315
Updates codebase to use `utils.get_required` instead of raising `RequiredPropertyMissing` directly. Also updates usages to always use `.get(some_prop)` instead of `[some_prop]` to ensure we get `RequiredPropertyMissing` instead of `KeyError`.

Use get_required to raise RequiredPropertyMissing when appropriate

---

CHANGELOG.md
pystac/extensions/label.py
pystac/summaries.py

These couple of issues were found while reviewing #561. VS Code running pylance/pyright showed some errors. This PR fixes errors that would be exposed to users using that tooling with PySTAC.
The first is straightforward, the setter of SummariesLabelExtension.label_properties was mis-typed.
The second is more subtle - for [structural typing](https://www.python.org/dev/peps/pep-0544/), it is required that the parameter names of the method in the Protocol be the same as the implementing type in order for type checking to pass. We defined a `Comparable` Protocol that required a method `__lt__(self, x: T) -> bool`, which was used as the bounds for the `RangeSummary` generic type. This works with things like floats and ints, which define their `__lt__` methods with the parameter name being …

Fix some type issues exposed via the API

---

CHANGELOG.md
docs/api.rst
pystac/extensions/item_assets.py
tests/data-files/item-assets/example-landsat8.json
tests/extensions/test_item_assets.py

- Closes #325
Updates docstrings and adds tests for the Item Assets Extension.

Update Item Assets Extension

---

docs/api.rst
pystac/extensions/datacube.py

- #324
Adds docstrings to Datacube Extension. Tests will be implemented in a separate PR post-1.0.0

Update Datacube Extension docstrings

---

CHANGELOG.md
pystac/catalog.py
tests/test_catalog.py

This PR allows to specify a folder where a catalog should be saved, to be used instead of the pth taken for the catalog self href
This will allow implementing the functionaity requested at https://github.com/stac-utils/stactools/issues/12
It is still a work in progress. I am creating this PR to share the approach and gather some feedback about it. I will add unit tests and implement the corresponding code in StacTools later.

Allow to save a catalog at a specific location

---

CHANGELOG.md
pystac/link.py
tests/data-files/file/item.json
tests/test_link.py

**Related Issue(s):** #571 
**Description:** Items created from relative paths can have relative self links, which breaks assumptions about self hrefs. Here's one place where the self href is assumed to be absolute: https://github.com/stac-utils/pystac/blob/76ef6a3b9bc3412cfcbc7f502d8fc1f56310b779/pystac/link.py#L234-L242
I did confirm that the issue was present in https://github.com/stac-utils/pystac/releases/tag/v1.0.0-rc.3, which means that #555 is likely _not_ the cause (we thought it might be since it did muck around with how links worked).
~Opening as a draft b/c it's just a failing test right now, will convert to a real pull request when there's a resolution.~

Relative self hrefs break link resolution

---

CHANGELOG.md
pystac/version.py

Bumps PySTAC version to 1.0.1. 
This patch release includes changes from #574.

Bump library version to 1.0.1

---

.github/workflows/continuous-integration.yml
CHANGELOG.md

**Related Issue(s):** https://github.com/stac-utils/pystac/pull/577#issuecomment-886879246
**Description:** When orjson doesn't have a wheel available for a given OS+Python, we have to build it from source during CI. This requires the rust compiler (and associated tooling). There was a minor regression in the output of the `--version` command in one rust tool (`cargo`) which caused the `orjson` build chain to break. When https://github.com/rust-lang/cargo/pull/9727 is incorporated back into nightly Rust releases we can unpin this toolchain and revert it back to `nightly`.
The check that was failing because of the regression:
https://github.com/PyO3/maturin/blob/5f134e3a4adbbf21f04c10f1dc9722742156f959/maturin/__init__.py#L114-L122
- ~[ ] Documentation has been updated to …

Pin rustc version to nightly-2021-04-27 in CI

---

CHANGELOG.md
setup.py

stac-utils/stactools#155
This includes type information in the packages so that users of `pystac` can utilize it. This is particularly useful if the downstream project uses `mypy` or any of its competitors.
- ~[ ] Documentation has been updated to reflect changes, if applicable~

Include typing information during packaging

---

CHANGELOG.md
pystac/version.py

Updates library version and CHANGELOG for a v1.1.0 release.

Bump library version to v1.1.0

---

CHANGELOG.md
mypy.ini
pystac/__init__.py
pystac/catalog.py
pystac/serialization/__init__.py
tests/extensions/test_scientific.py
tests/utils/__init__.py

- #582
Avoids implicit re-exports by using `__all__` in `__init__.py` files where we intentionally re-export values and removing references to other implicitly re-exported values.
This also allows us to enable `strict = True` for `mypy`.

Avoid implicit re-exports

---

CHANGELOG.md
pystac/link.py
tests/test_link.py

- Closes #358 
Gets `Link.title` from the target object (`Link._target_object`) when `title` is `None` and it is possible to do so.
**TODO:**

Get link title from target, when possible

---

CHANGELOG.md
docs/concepts.rst
pystac/catalog.py
pystac/layout.py
tests/test_catalog.py

**Related Issue(s):** #480 
Fix `Catalog.generate_subcatalogs()` to allow for better control on the subcatalogs:
* subfolders can include multiple template values (e.g. using "${property1}_${property2}" will add a single subfolder layer);
* subfolders that are common to all items can be setup directly via the template (e.g. "2021-08-04/${property1}" will add the `2021-08-04` subcatalog for all items, without having to use the `defaults` argument)

Better control on subfolders in `generate_subcatalogs`

---

CHANGELOG.md
pystac/extensions/label.py
tests/extensions/test_label.py

**Related Issue(s):** n/a
**Description:** Per https://mypy.readthedocs.io/en/stable/common_issues.html#variance,
`List` is invariant, so the LabelClasses.classes type annotation is
unncessarily strict. This commit relaxes the type annotation to use
`Sequence`, including a simple unit test.
- ~[ ] Documentation has been updated to reflect changes, if applicable~

Use Sequence for annotations for label classes

---

CHANGELOG.md
docs/api.rst
pystac/__init__.py
pystac/extensions/table.py
tests/data-files/table/README.md
tests/data-files/table/collection-2.json
tests/data-files/table/collection.json
tests/data-files/table/item.json
tests/data-files/table/table-collection.json
tests/extensions/test_table.py

Added support for the Table-extension by @TomAugspurger:
https://github.com/stac-extensions/table

Extension/Table - Added extension

---

setup.py

Support for 3.10 was added in https://github.com/stac-utils/pystac/pull/656
This ensures that packages will be marked as supporting 3.10
- ~[ ] Documentation has been updated to reflect changes, if applicable~
- ~[ ] Changes are added to the [CHANGELOG](https://github.com/stac-utils/pystac/blob/main/CHANGELOG.md). See [the docs](https://pystac.readthedocs.io/en/latest/contributing.html#changelog) for information about adding to the changelog.~

Packaging: Add Trove Classifier for Python 3.10

---

.gitignore
CHANGELOG.md

None
Adds `.python-version` files (used by `pyenv` and `pyenv-virtualenv` to set a local Python environment) to the `.gitignore` file.

gitignore .python-version file

---

CHANGELOG.md
pystac/catalog.py
pystac/extensions/datacube.py
pystac/extensions/file.py
pystac/extensions/label.py
pystac/extensions/pointcloud.py
pystac/extensions/raster.py
pystac/extensions/sar.py
pystac/extensions/sat.py
pystac/extensions/scientific.py
pystac/extensions/version.py
pystac/media_type.py
pystac/provider.py
pystac/rel_type.py
pystac/stac_object.py
pystac/utils.py
tests/test_link.py

- Closes #652 
- Closes #626
Creates a `StringEnum` class that overwrites the default `__str__` method to return the value of the enum. All instances of classes inheriting from `str` and `Enum` have been updated to inherit from this base class, including `RelType`.

Fix string enum serialization

---

CHANGELOG.md
pystac/catalog.py
pystac/stac_object.py
tests/test_catalog.py
tests/utils/test_cases.py

**Related Issue(s):** #657
Adds a unit test that tests #657 
I notcied that there is an issue only with catalogs of the full hierarchy:
* catalog
* collection
* item
The following one works as expected:
* catalog
* item

Add an extra SELF_CONTAINED catalog test

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
pystac/item.py
pystac/item_collection.py
pystac/link.py
pystac/stac_io.py
pystac/stac_object.py
tests/test_item_collection.py
tests/utils/stac_io_mock.py

**Related Issue(s):** #546
This PR adds a flag to the `to_dict` methods of STACObjects and ItemCollection, along with Link, to skip the logic that looks to the root catalog type to determine if hierarchical link HREFs should be relative or absolute. 
The current implementation always checks the link's owner for a root catalog, and if it exists and if that root catalog is of type RELATIVE_PUBLISHED or SELF_CONTAINED, and that link is a hierarchical link, then the link's href is transformed to be relative to the link's owner's root catalog.
The default option is to maintain this behavior for the default to_dict method, along with the Catalog, Collection and Item to_dict methods; but this flag now allows users to skip this link href transformation, saving reads.
The …

Allow PySTAC to skip transforming hrefs to relative or absolute based on CatalogType

---

CHANGELOG.md
pystac/version.py

Updates to package version and CHANGELOG for v1.2.0 release.
TODO:

Changes to main for v1.2.0 release

---

CHANGELOG.md
pystac/utils.py
tests/test_utils.py

**Related Issue(s):** https://github.com/stac-utils/pystac-client/issues/113.
**Description:** The very basic case of `make_absolute_href(href, None, None)` was broken if `href` was a url. This fixes that breakage with a test case to demonstrate.

Make absolute hrefs from urls

---

CHANGELOG.md
pystac/extensions/file.py
tests/extensions/test_file.py

- Closes #605 
Converts `List[MappingObject]` to `List[Dict[str, Any]]` in the `FileExtension.values` setter. Also adds `from_dict` and `to_dict` methods to the `MappingObject` class.

Store file:values as list of dicts in Item properties

---

CHANGELOG.md
docs/api.rst
pystac/cache.py
pystac/catalog.py
pystac/collection.py
pystac/extensions/eo.py
pystac/extensions/file.py
pystac/extensions/hooks.py
pystac/extensions/item_assets.py
pystac/extensions/label.py
pystac/extensions/pointcloud.py
pystac/extensions/raster.py
pystac/extensions/scientific.py
pystac/extensions/version.py
pystac/item.py
pystac/layout.py
pystac/serialization/identify.py
pystac/stac_object.py
pystac/summaries.py
pystac/validation/stac_validator.py

- Closes #321 
Adds type annotations for instance attributes for all classes. Where the class docstring had an `Attributes` section, I removed those and added a docstring on each type annotation.

Add instance attribute annotations to all classes

---

CHANGELOG.md
pystac/extensions/datacube.py
tests/data-files/datacube/item.json
tests/extensions/test_datacube.py

- Closes #681
- Begins to address #324 
Adds a setter for the `DatacubeExtension.variables` property and adds a `Variable.to_dict` method. Also adds tests for getting and setting `DatacubeExtension.variables`.

Add variables setter to datacube extension

---

CHANGELOG.md
docs/concepts.rst

- #602
Adds a note to the Concepts docs describing how to access extension properties that makes it more clear that `.ext` will raise an exception if the object does not already implement the extension.

Add note on possible exceptions to extensions docs

---

CHANGELOG.md
docs/tutorials/creating-a-landsat-stac.ipynb

- Closes #665
Updates the Landsat tutorial to be up-to-date with the current extensions and StacIO APIs.

Update Landsat tutorial

---

CHANGELOG.md
pystac/catalog.py
tests/test_catalog.py

- Closes #713
Fixes the paths to which sub-catalogs are saved by ensuring that the `dest_href` argument to `Catalog.save` is a directory when called on child catalogs.

Fix paths to saved sub-catalogs

---

.readthedocs.yaml
CHANGELOG.md

N/A
Uses zipped HTML instead of PDF as our downloadable documentation format since PyData theme does not support LateX builds (we had already disabled PDF builds due to another issue with packaging the notebooks). This will provide a downloadable version of the docs that mimics our online docs as closely as possible.

Build zipped HTML instead of PDF

---

CHANGELOG.md
docs/tutorials.rst

- #711
Fixes link to PySTAC Introduction tutorial in tutorials index page.
cc: @KennSmithDS

Fix PySTAC Introduction tutorial link

---

CHANGELOG.md
pystac/catalog.py
tests/test_catalog.py

- Closes #597 
Fixes issue where self links were included in Items for "relative published" catalogs.

No self links in relative published items

---

CHANGELOG.md
docs/tutorials.rst
docs/tutorials/adding-new-and-custom-extensions.ipynb

- Closes #384
Updates the "Adding New and Custom Extensions" tutorial to be up-to-date with the new extensions API. The tutorial covers implementation of a `PropertiesExtension` sub-class that operates on Items, but does not cover summaries (a separate tutorial on creating summaries in general may be in order anyway).
Also updates the order of the TOC in the `tutorials*` pages to match the order of the tutorials in the index page.

Update tutorial on adding new extensions

---

.github/workflows/continuous-integration.yml

None
#731 introduced a bug to the CI config by leaving out the `experimental` property in the test matrix. This was causing none of the test matrix jobs to run. This PR fixes that regression.

Fix CI config

---

CHANGELOG.md
pystac/collection.py
tests/test_collection.py

- Closes #586 
Adds 2 type variables that are used in the `TemporalExtent` class:
- `TemporalIntervals` - This is used for properly formatted [STAC temporal intervals](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#temporal-extent-object) (i.e. a list of lists)
- `TemporalIntervalsLike` - This is used for the `intervals` argument to `TemporalExtent` where we allow either a list of lists or a list of optional datetimes and convert it into a list of lists.
I tried using a covariant `TypeVar` as I had initially suggested in [#586 (comment)](https://github.com/stac-utils/pystac/issues/586#issuecomment-889199716), but that did not fix the type errors. Using a `Union` type of all the possible combinations seemed to …

Use type alias for temporal intervals

---

CHANGELOG.md
pystac/catalog.py
tests/test_catalog.py

Closes #666
Add the possibility of providing a `StacIO` instance to write out a catalog, as useful e.g. to read from and write to different file systems. 

`stac_io` as argument to `Catalog.save`

---

CHANGELOG.md
docs/api/extensions/storage.rst
pystac/__init__.py
pystac/extensions/eo.py
pystac/extensions/storage.py
tests/data-files/storage/collection-naip.json
tests/data-files/storage/item-naip.json
tests/extensions/test_storage.py

- Closes #734 
Implements the Storage Extension, including tests + docs.

Implement Storage Extension

---

CHANGELOG.md
pystac/extensions/base.py

- Closes #634 
Clarifies the error message when someone tries to use `add_if_missing=True` on an `Asset` with no owner.

Clarify error using add_if_missing on ownerless asset

---

CHANGELOG.md
docs/api/serialization/identify.rst
docs/api/utils.rst
docs/conf.py
mypy.ini
pystac/extensions/datacube.py
pystac/extensions/eo.py
pystac/extensions/file.py
pystac/extensions/item_assets.py
pystac/extensions/label.py
pystac/extensions/pointcloud.py
pystac/extensions/projection.py
pystac/extensions/raster.py
pystac/extensions/sar.py
pystac/extensions/sat.py
pystac/extensions/scientific.py
pystac/extensions/table.py
pystac/extensions/timestamps.py
pystac/extensions/version.py
pystac/extensions/view.py
pystac/utils.py

- Closes #249
Updates docstrings with references to internal and external API docs and adds more detail to some of the docstrings.

Update pystac.utils docs

---

CHANGELOG.md
pystac/version.py

Updates CHANGELOG and package version for the v1.4.0 release.

Update version and changelog for v1.4.0 release

---

CHANGELOG.md
pystac/link.py

**Related Issue(s):** #742 
Updated edge case for when `stac_io is None`, `owner is not None` and instance is not `pystac.Catalog`. Desired behavior now fetches the root of the owner to update the `stac_io` of a `Link` object.
- [N/A] Documentation has been updated to reflect changes, if applicable

update stac_io from owner root

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
pystac/extensions/item_assets.py
tests/extensions/test_eo.py
tests/extensions/test_item_assets.py

Fixes https://github.com/stac-utils/pystac/issues/576
* Adds missing create and apply to Asset Definition
* Enhances an unrelated unit test, which I noticed while comparing other code (test_eo.py)
* Fixes old commonmark version in some docstrings.
* Fixes docstrings referencing RC of stac spec.

Fix/576 AssetDefinition missing create, apply

---

.github/workflows/continuous-integration.yml

None
Updates the Python 3.11 alpha release version in the CI to the latest available in GitHub Actions (3.11.0-alpha.6).

Update Python 3.11 alpha-release in CI

---

CHANGELOG.md
pystac/extensions/datacube.py
tests/extensions/test_datacube.py

- Fixes #781
- Helps with #324
An optional argument is added to the `DatacubeExtension.apply` method called `variables` and handed off to the variable setter. The argument is optional because Variable Objects are optional in the datacube extension spec.
A new `test_apply_variables` method for the `DatacubeTest` class does a round-trip check on a variable present in the example item using `apply`.

Add variables argument to the DatacubeExtension `apply` method

---

.github/workflows/continuous-integration.yml

Updates CI config to use Python 3.11.0-alpha.7. This should fix the failing builds for these jobs.

Update CI to use Python 3.11.0-alpha.7

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
pystac/summaries.py
tests/extensions/test_scientific.py
tests/test_collection.py
tests/test_summaries.py

**Related Issue(s):** Fixes #787 
**Description:** Makes sure that all the mutable properties of a `Collection` get deepcopied when the collection is cloned. Implements `clone` on `Summaries` to make sure cloned collection will point to a new instance of `Summaries` after being cloned.
I have some weird mypy errors from the tests that I added. Still trying to figure out how to fix. I would love some help on that.
- [NA] Documentation has been updated to reflect changes, if applicable

Deepcopy Collection properties on clone

---

CHANGELOG.md
pystac/extensions/grid.py
setup.cfg
tests/data-files/examples/1.0.0/example-sentinel2.json
tests/data-files/examples/example-info.csv
tests/data-files/grid/example-sentinel2.json
tests/extensions/test_grid.py

- #783
Add Grid Extension support <https://github.com/stac-extensions/grid/>

add Grid Extension support

---

mypy.ini
pystac/asset.py
tests/test_item.py

**Related Issue(s):
* Closes #754 
`Asset.get_absolute_href` now returns `None` when the owning `Item` has no self HREF.

Return None from Asset.get_absolute_href when owning Item self HREF is NOne

---

CHANGELOG.md
pystac/extensions/raster.py
tests/data-files/raster/raster-planet-example.json
tests/data-files/raster/raster-sentinel2-example.json
tests/extensions/test_raster.py

**Related Issue(s):** #789 
Makes "nan", "inf", and "-inf" valid values for the `nodata` property in `raster:bands`.
- update schema uri
- align the `nodata` type with the updated schema, which allows for numeric and "nan", "inf", and "-inf" strings.
- update tests and test data. For the test data, the `raster:bands` object added to the `B09` asset is from the sentinel example in the Raster Extension repo.

update raster extension to v1.1.0

---

CHANGELOG.md
pystac/asset.py
tests/test_item.py

- Closes #820 
Uses `deepcopy` on `Asset.extra_fields` when cloning so that mutating the cloned Asset's extra fields does not mutate the original asset.

Deepcopy Asset.extra_fields when cloning

---

CHANGELOG.md
pystac/collection.py
pystac/item.py
tests/test_collection.py
tests/test_item.py

- Closes #747 
Adds an `assets` argument to `Item.__init__` and `Collection.__init__` that accepts a dictionary mapping strings to `Asset` objects, which allows us to attach Assets to these objects as part of instantiation. 
Also preserves Collection assets when using `Collection.clone` and adds regression test.
cc: @cholden-ag

Preserve Collection assets on clone

---

docs/tutorials/how-to-create-stac-catalogs.ipynb

I have fixed a small typo and a wrong code snippet.
Indeed the 26th cell is
```
with open(item.self_href) as f:
print(f.read())
```
But it should be the `catalog` object that is read.

Fix typo + wrong code

---

.github/workflows/continuous-integration.yml
CHANGELOG.md
requirements-test.txt

Should unblock #895, #882, and others.
Dependency resolution was broken for `pip install -r requirements-dev.txt`:
```sh
$ pip install -r requirements-dev.txt
... snip ...
ERROR: Cannot install -r ./requirements-docs.txt (line 2), -r ./requirements-docs.txt (line 4), -r ./requirements-docs.txt (line 5), -r ./requirements-docs.txt (line 6) and -r ./requirements-test.txt (line 9) because these package versions have conflicting dependencies.
The conflict is caused by:
sphinx 4.5.0 depends on docutils<0.18 and >=0.14
nbsphinx 0.8.9 depends on docutils
pydata-sphinx-theme 0.8.1 depends on docutils!=0.17.0
sphinx-panels 0.6.0 depends on docutils
doc8 1.0.0 depends on docutils<0.21 and >=0.19
```
This wasn't caught by CI because we never install …

Fix dependencies

---

CHANGELOG.md
docs/concepts.rst
pystac/stac_io.py
tests/test_stac_io.py

**Related Issue(s):** #886
This PR aims to address #886 by adding a mechanism for adding headers for StacIO requests.
The suggested approach for using this:
```python
from pystac import StacIO
stac_io = StacIO.default()
stac_io.headers = {"Authorization": "<some-authn-header>"}
catalog = Catalog.from_file("<some-href-that-requires-authn>", stac_io=stac_io)
```
You could also just directly instantiate the `StacIO` or `DefaultStacIO` class, with headers included as an arg. 

Add a mechanism for adding headers to StacIO requests

---

CHANGELOG.md
docs/concepts.rst

There is a bug in documentation in an example of a custom `StacIO` class caused by a mismatch of argument and variable names. This PR fixes it.

DOC: fix bug in custom StacIO example

---

pystac/extensions/table.py

seems like a small typo. Currently, the link is rendered and constructed incorrectly.

fix broken link

---

CHANGELOG.md
pystac/extensions/grid.py
tests/data-files/grid/example-landsat.json
tests/data-files/grid/example-sentinel2.json

n/a
- Updates pystac to use Grid Extension v1.1.0 and fixes the grid:code regex to allow alphanumeric prefixes instead of only alphabetic prefixes

update to Grid Extension v1.1.0, fix grid:code prefix regex, add Landsat test

---

tests/extensions/test_grid.py

Type error found with Pyre
"filename": "tests/extensions/test_grid.py"
"warning_type": "Incompatible attribute type [8]"
"warning_message": " Attribute `code` declared in class `GridExtension` has type `str` but is used as type `None`."
"warning_line": 89
"fix": None to ""

Attribute `code` has type `str` but is used as type `None`

---

CHANGELOG.md
pystac/utils.py
tests/test_utils.py

- Helps fix https://github.com/stac-utils/pystac/issues/927
Currently `datetime_to_str` function in `utils` truncates all microseconds if the microsecond in `datetime` object is equal to zero.
I've added an optional input (`timespec`) to control this ability. The default behavior is like before, but If users want to retrieve the result with `microseconds`, they can pass `timespec = "microseconds"` to the `datetime_to_str` function, and the result with microseconds will return.

Add timespec to datetime_to_str util function.

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
tests/test_collection.py

The underlying problem is that, when creating a Collection from a dict, some values are pulled out to Collection-level attributes, e.g. https://github.com/stac-utils/pystac/blob/114b1a192051972cf155c36c362ad5628572215a/pystac/collection.py#L644-L646
However, those values are _not_ removed from the original dictionary `d`, and that original dictionary is used to populate `extra_fields`: https://github.com/stac-utils/pystac/blob/114b1a192051972cf155c36c362ad5628572215a/pystac/collection.py#L657
This means that the `assets` attribute of a Collection isn't the only place where assets (and other attributes) are stored, and in fact when a collection is turned back into a dictionary, those assets are re-populated from `extra_fields`: …

Fix serializing optional Collection attributes

---

CHANGELOG.md
pystac/media_type.py

#763 
Adds a media type for flatgeobuf data.

Add flatgeobuf media type

---

CHANGELOG.md
pystac/asset.py
pystac/collection.py
pystac/item.py
tests/data-files/collections/with-assets.json
tests/data-files/item/sample-item.json
tests/test_collection.py
tests/test_item.py

#873 
Adds ability to filter Item and Collection Assets by media_type and role via `get_assets()` method.

Add filter to  Item and Collection `get_assets` method

---

README.md
docs/contributing.rst

Remove some 3.11-specific language from the README that no longer applies. Specifically, orjson wheels exist for all three os flavors for Python 3.11
Also includes a couple sidecar fixups to the README caught by my markdown linter.

Fix up README for Python 3.11

---

README.md
docs/installation.rst

**Related Issue(s):** #917 
**Description:** I copied the pypi installation section and then pointed to the installation docs to avoid duplication. In this PR I just deleted the NEP-29 information, but I think it would also fit nicely in the contributing doc if you think it's important to keep around.

Simplify installation section of readme

---

CHANGELOG.md
pystac/catalog.py
tests/test_catalog.py

- Closes #284
Adds a `skip_unresolved` argument to `Catalog.normalize_hrefs` and `Catalog.normalize_and_save`. Instead of using `Catalog.get_items` and `Catalog.get_children` (which resolve their links), we re-implement with additional logic to conditionally skip unresolved links. We considered pushing `skip_unresolved` all the way down into `Link.get_stac_object`, but this seemed like overkill, since the motivating use-case for `skip_unresolved` is to avoid walking the whole tree when normalizing (#284).
Because `save` already skips unresolved links, this enables `normalize_and_save` to only touch objects that have been added to the tree or modified (and therefore resolved).
Note this isn't exactly the solution proposed by @matthewhanson in #284, …

Normalize hrefs while skipping unresolved links

---

CHANGELOG.md
docs/concepts.rst
pystac/item.py
tests/test_item.py

- Closes #786 
Adds `__geo_interface__` for items, collections, and spatial extent. Includes a `pystac.utils.box` function that cribs from shapely, with a couple of tweaks. Collection and spatial extent geo interfaces are impelemented per @duckontheweb's suggestion (if `len(bboxes) == 1`, use that as a Polygon; if `len(bboxes) > 1`, use `bboxes[1:]` as a MultiPolygon).
I can see @philvarner's point that we're making an opinionated decision w.r.t. the Collection geointerface that may not be correct. It'd be good to get other's opinions on the correct Collection approach, and if there's disagreement it may make sense to remove it from this PR and put that decision off until later. I've pulled in a couple of reviewers for that reason.

Add __geo_interface__ for items

---

CHANGELOG.md
tests/extensions/test_label.py
tests/test_catalog.py

- Closes #502 
- Depends on #909 
Fixes two tests that looped through iterators twice.

Fix twice consumed iterators

---

CHANGELOG.md
pystac/validation/stac_validator.py
tests/data-files/item/sample-item-with-relative-extension-path.json
tests/data-files/schemas/v1.0.0-projection.json
tests/test_item.py

There's nothing in the specification that disallows relative stac_extension paths, so we should allow it. This commit uses make_absolute_href on all schema uris.
I use the projection extension for the unit test, but I modified the jsonschema to not require the absolute URI of the schema in `stac_extensions`.

Allow relative stac_extension paths

---

CHANGELOG.md
pystac/stac_object.py
tests/test_catalog.py

- Closes #937 
Enables filtering with `get_links()` on either `rel`, `media_type`, or both.

Filter links with only media_type

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
pystac/layout.py
pystac/stac_object.py

- Closes #965 
- Updates docstrings to make users aware of the default layout strategy.
- Adds an optional `strategy` parameter to the catalog `add_items()` method.
- Updates docstring formatting in several places to correct rendering in the API docs.

Make `layout_strategy` default value consistent

---

CHANGELOG.md
pystac/item.py
tests/test_item.py

- Closes #905 
- Closes #710 (though with a different solution than the one proposed there)
It's pretty awkward to provide `start_datetime` and `end_datetime` as strings in `properties`, when you can provide a datetime object as `datetime`. This PR adds two optional arguments to set `start_datetime` and `end_datetime` in the constructor. These values will override anything set in `properties`.

Add start and end datetimes to `Item.__init__`

---

.github/workflows/continuous-integration.yml
CHANGELOG.md
pystac/__init__.py
pystac/asset.py
pystac/cache.py
pystac/catalog.py
pystac/collection.py
pystac/extensions/datacube.py
pystac/extensions/eo.py
pystac/extensions/file.py
pystac/extensions/grid.py
pystac/extensions/hooks.py
pystac/extensions/item_assets.py
pystac/extensions/label.py
pystac/extensions/pointcloud.py
pystac/extensions/projection.py
pystac/extensions/raster.py
pystac/extensions/sar.py
pystac/extensions/sat.py
pystac/extensions/scientific.py
pystac/extensions/storage.py
pystac/extensions/table.py
pystac/extensions/timestamps.py
pystac/extensions/version.py
pystac/extensions/view.py
pystac/serialization/identify.py
pystac/serialization/migrate.py
pystac/stac_object.py
pystac/validation/__init__.py

- Supports #862
**Tl;dr:**
Switch to using `from __future__ import annotations` to give us slightly cleaner type signatures.
As described in the [mypy documentation](https://mypy.readthedocs.io/en/stable/runtime_troubles.html), there are three tools at our disposal when resolving runtime typing issues:
- `from __future__ import annotations`
- String types
- `typing.TYPE_CHECKING`
Currently, **pystac** uses string types and `typing.TYPE_CHECKING`. This works fine, but does lead to a bit of clutter in the typing namespace, e.g.: https://github.com/stac-utils/pystac/blob/f44de3ca86a8bc1cc1af19add4ac220fd0300365/pystac/asset.py#L8-L11
`"Item_Type"` and friends work fine for the purposes of defining our type signatures, but (IMO) they feel like a …

Use `from __future__ import annotations`

---

CHANGELOG.md
pystac/utils.py
tests/test_utils.py

**Related Issue(s):** n/a
There are a number of places in the STAC ecosystem where datetimes are converted two and from RFC 3339 strings. Many of these places are doing this incorrectly. These changes aim to add a correct implementations to:
- rfc3339_str_to_datetime: parse ONLY a valid RFC 3339 string to a datetime
- str_to_interval: parse an interval string into a datetime tuple
- now_in_utc: create a datetime with UTC set as the datetime (since utcnow() inexplicably does not do this)
- now_to_rfc3339_str: create an RFC3339 string representing now
My primary motivation is to replace the numerous uses of the stac_pydantic constant `DATETIME_RFC339`(sic) with uses of these methods. Other libraries that depend on pystac will also use them, and there are likely several …

Add helper methods for RFC 3339 datetime handling

---

.github/workflows/continuous-integration.yml

This is a minor workflow improvement where github actions are automatically cancelled if you push another commit to the branch. It can help with speeding up CI runs.
Example: https://github.com/jsignell/pystac/actions/runs/4186696525

Cancel running jobs on github actions

---

benchmarks/catalog.py
benchmarks/extensions/projection.py
docs/contributing.rst
pystac/common_metadata.py
pystac/extensions/sat.py
pystac/extensions/timestamps.py
pystac/item.py
tests/conftest.py
tests/extensions/test_custom.py
tests/extensions/test_grid.py
tests/extensions/test_sar.py
tests/extensions/test_sat.py
tests/extensions/test_scientific.py
tests/extensions/test_version.py
tests/test_link.py

**Description:** 
Just a minor tidy. The datetime import varied across the codebase so I took the opportunity to consolidate around `from datetime import datetime`. 

Always use ``from datetime import datetime``

---

CHANGELOG.md
pystac/item.py
tests/test_item.py
tests/test_item_collection.py

**Related Issue(s):** #831
The easy solution to better error handling is to just defer until the init. So I added pop defaults to all the dict fields _even if they are required_

Add defaults to all the `Item.from_dict` pops

---

CHANGELOG.md
pystac/link.py
pystac/stac_object.py
tests/conftest.py
tests/test_catalog.py
tests/test_collection.py
tests/test_item.py
tests/test_link.py

- Closes #179 
- Begins adding fixtures for #948, and changes fixture names as recommended in https://github.com/stac-utils/pystac/issues/948#issuecomment-1433176507
- Adds `remove_hierarchical_links` to `STACObject`
- Adds `Links.is_hierarchical`
I personally prefer the term "structural", but "hierarchical" was already in use so I stuck with that: https://github.com/stac-utils/pystac/blob/a573835eb49f1ba9c9ccdf06fa105ad1a7500624/pystac/link.py#L27-L34
Includes the first pytest fixture for the test cases. I went for a more descriptive catalog name (`label_catalog`) instead of `test_case_1` -- my thought is that it'll be nicer to depend on a well-named fixture rather than some arbitrary numbering scheme. I also followed @jsignell's recommendation and …

Remove structural links

---

CHANGELOG.md
pystac/extensions/item_assets.py
tests/extensions/test_item_assets.py

Add extra_fields to AssetDefinition

---

.github/pull_request_template.md
CHANGELOG.md
README.md
pystac/catalog.py
tests/conftest.py
tests/test_catalog.py
tests/test_collection.py
tests/test_item.py

- Closes #478 
Pretty simple, we just use `Catalog.walk`.
Sidecar fixes:
- Tweak to the PR template to put the related items in a list by default -- this is how you need to format things to activate [closing keywords](https://docs.github.com/articles/closing-issues-using-keywords)
- Make the build status badge in the README a link

Add Catalog.fully_resolve

---

CHANGELOG.md
docs/Makefile
docs/api.rst
pystac/__init__.py
pystac/errors.py
pystac/layout.py
requirements-docs.txt
tests/test_layout.py

- Closes #685
Duplicates `TemplateError` from `layout.py` to `errors.py` and updates all references to point to the definition in `errors.py`. All custom exceptions are now in `errors.py`. Per #685, the existing `TemplateError` remains in `layout.py` but is now marked as deprecated and noted that it will be removed in the next major release (2.0.0).

Move TemplateError to errors.py

---

tests/test_item_collection.py

- Until #960 is fixed, the default behavior is to hit the network when serializing items.
We often have intermittent test failures due to an inability to hit CMR, e.g. https://github.com/stac-utils/pystac/actions/runs/4306838650/jobs/7511161952#step:5:321. In this case, the network request is unnecessary for the test that is running, so we diable the network request by setting `transform_hrefs=False` when serializing items.
I'm sure there's other spots where we could improve things by setting `transform_hrefs=False`, but rather than do a complete audit, I'd like to fix them as we find them from failed test runs.

Don't transform hrefs in one test

---

CHANGELOG.md
pystac/item_collection.py
tests/test_item_collection.py

- closes #859 
NOTE this PR changes the behavior when adding item collections. After this PR adding item collections will no longer dedupe items. 

When instantiating ItemCollections clone items by default

---

CHANGELOG.md
README.md
benchmarks/item.py
pystac/__init__.py
pystac/collection.py
pystac/errors.py
pystac/extensions/version.py
pystac/item.py
tests/extensions/test_version.py

- Closes #843 
- Inserts logic into the Item and Collection `from_dict()` methods that checks for the version extension and, if it exists, issues a `DeprecatedWarning` if the version extension `deprecated` field is set to `True`.
- Provides an `ignore_deprecated` context manager to suppress the `DeprecatedWarning`.
This PR originally used logic outside the version extension to check for the `deprecated` field on assets. This was removed in favor of working within the version extension's current deprecation checking ability.

Add deprecation warnings

---

.github/workflows/release.yml
RELEASING.md

I didn't get the release flow quite right for https://github.com/stac-utils/pystac/releases/tag/v1.7.0, so this fixes up the docs for next time, and tweaks the workflow to run on `publish` (and not just `created`, since `created` only fires if you make a new tag).

Fix up releasing workflow and docs

---

.github/pull_request_template.md

I don't think it is good practice to encourage people to run `pre-commit run --all-files`. It kind of undermines the beauty of pre-commit which is that it runs by default on the diff on each commit.

Update PR template since precommit runs on the diff by default

---

.flake8
.pre-commit-config.yaml
CHANGELOG.md
docs/contributing.rst
pyproject.toml
requirements-test.txt

- Closes #1030
[ruff](https://github.com/charliermarsh/ruff) is fast and has [good momentum](https://github.com/charliermarsh/ruff#whos-using-ruff). See https://beta.ruff.rs/docs/faq/#which-tools-does-ruff-replace for the list of tools that **ruff** can replace.

Replace flake8 and isort with ruff

---

CHANGELOG.md
pystac/item.py
tests/test_item.py

- Closes #1048 
`__geo_interface__` should be the feature, not just the geometry. I misread the protocol on my first implementation. I made the choice to just call `to_dict` with all the dials set to no to make it as quick and light as possible. An alternative implementation would be to build a new dict with only the `__geo_interface__` required fields (`type`, `bbox`, `properties`, `geometry`, `coordinates`).

Fix __geo_interface__

---

CHANGELOG.md
docs/quickstart.ipynb
docs/tutorials/how-to-create-stac-catalogs.ipynb
pystac/catalog.py
pystac/collection.py
pystac/summaries.py
setup.cfg
tests/conftest.py
tests/extensions/test_label.py
tests/extensions/test_pointcloud.py
tests/extensions/test_projection.py
tests/extensions/test_timestamps.py
tests/extensions/test_version.py
tests/extensions/test_view.py
tests/test_catalog.py
tests/test_collection.py
tests/test_item.py
tests/test_layout.py
tests/test_summaries.py
tests/validation/test_validate.py

- #585
Instead of using `get_all_items` people should use `get_items(recursive=True)` and instead of `Catalog.get_item(id)` people should use `next(Catalog.get_items(id), None)`
**TO DO:**

Expand `get_items` - deprecate `get_all_items` and `Catalog.get_item` 

---

CHANGELOG.md
pystac/collection.py
pystac/item.py
tests/test_collection.py
tests/test_item.py

- #541
~Instead of making a shallow copy, just return the object itself.~ Always create a new dict and deepcopy all values
I grepped around for other places where `dict` or `.copy` are used, and this was all I found

Return deepcopy of `assets` from `get_assets`

---

CHANGELOG.md
pystac/__init__.py
pystac/extensions/base.py
pystac/extensions/grid.py
pystac/extensions/label.py
pystac/extensions/projection.py
pystac/extensions/raster.py
pystac/serialization/migrate.py
tests/conftest.py
tests/extensions/test_grid.py
tests/extensions/test_label.py
tests/extensions/test_projection.py
tests/extensions/test_raster.py

- #1084
From issue: 
> In https://github.com/stac-utils/pystac/pull/1081 we added support for older schema URIs to the `ProjectionExtension`. This behavior should be generalized so other extensions can use it easily. Ideas:
> 
> - Add `get_schema_uris()` to the base mixin
> - Refactor the base `has_extension()` to check against `get_schema_uris()` instead of `get_schema_uri()`
> - Backport any extensions that have older-but-compatible schema uris (thinking maybe `label` at least?)
> 
> This doesn't solve the problem, it's more of a band-aid -- if a newer version of an extension is incompatible with the Python structure, we don't have a mechanism to "migrate".
> 
> xref #448 which is our tracking issue for the general problem of extension versions.
I …

 Expand support for multiple extension uris

---

CHANGELOG.md
docs/api.rst
docs/api/extensions/mgrs.rst
pystac/__init__.py
pystac/extensions/mgrs.py
tests/conftest.py
tests/data-files/mgrs/item.json
tests/extensions/test_mgrs.py

- #778
Code from: https://github.com/stactools-packages/sentinel2/blob/main/src/stactools/sentinel2/mgrs.py
Example from: https://github.com/stac-extensions/mgrs/blob/main/examples/item.json
Added pytest-style tests, docs

Add MGRS Extension from code in stactools-package for sentinel2

---

CHANGELOG.md
docs/concepts.rst
pystac/stac_io.py

I was running through the examples on pystac-client and came across some where you turn on logging and get to see all the requests that are being made. This seems like a nice way to increase visibility into what pystac is doing:
```python 
from pystac import Catalog
import logging
logging.basicConfig()
logger = logging.getLogger('pystac')
logger.setLevel(logging.DEBUG)
Catalog.from_file('https://planetarycomputer.microsoft.com/api/stac/v1')
```

Add debug logging on GET

---

CHANGELOG.md
pystac/item.py
tests/conftest.py
tests/test_item.py

- Fixes #1102
The `self` link is set in the constructor, so `from_dict` doesn't need to add the link again. This PR is against the v1.7 branch so we can use it to release a bugfix v1.7.3.

Remove duplicate self links on items

---

CHANGELOG.md
pystac/version.py
setup.py

Bugfix release to get #1103 out. Includes a small backport to fix #1085 for the 1.7 lineage. After this PR is merged, the **1.7** branch should be manually merged into main.

Release v1.7.3

---

CHANGELOG.md
pystac/stac_io.py
tests/test_stac_io.py

- Closes #1106 
This is in DefaultStacIO ... other StacIOs could support writing to urls, if they want. cc @constantinius.

Raise error if writing to url

---

CHANGELOG.md
pystac/serialization/migrate.py
tests/serialization/test_migrate.py

**Description:** I noticed recently while working on VEDA (https://staging-stac.delta-backend.com/) that if `stac_extensions` is set to null, with https://github.com/stac-utils/pystac/pull/1091 the collection can't be opened so as not to break people who might have have this mild invalidity in their catalogs. 
NOTE: I none of these collections with `stac_extensions` set to null fail validation because by the time you have created a collection from a dict and then dumped it back to a dict null has been stripped out.
**Example:**
```python
from pystac import Catalog
catalog = Catalog.from_file('https://staging-stac.delta-backend.com/')
failed = []
for c in catalog.get_collections():
try:
c.validate()
except:
failed.append(c)
```
```python-traceback …
```

Allow nullable `stac_extensions`

---

CHANGELOG.md
pystac/link.py
tests/test_link.py

I know this issue is closed, but I think this PR does what the OP intended.
- #652
I just encountered this recently when checking how a dict roundtrips. This is what I was doing:
```python
import pystac
import requests
response = requests.get("https://staging-stac.delta-backend.com/collections/no2-monthly-diff")
collection_dict = response.json()
collection_dict["links"]
```
```python
[{'rel': 'items',
'type': 'application/geo+json',
'href': 'https://staging-stac.delta-backend.com/collections/no2-monthly-diff/items'},
{'rel': 'parent',
'type': 'application/json',
'href': 'https://staging-stac.delta-backend.com/'},
{'rel': 'root',
'type': 'application/json',
'href': 'https://staging-stac.delta-backend.com/'},
{'rel': 'self',
'type': 'application/json', …
```

`Link.to_dict()` should only contain strings

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
tests/test_catalog.py

- #1116
Adds a `keep_parent` parameter to `add_child` and `add_item` to allow keeping the current parent if one is set. This makes the add calls more predictable while keeping backward compatibility.

Add keep_parent parameter to add_child and add_item #1116

---

.github/workflows/continuous-integration.yml
asv.conf.json

**Related issues:**
- Closes #1121 
**asv** expects `setup.py` so we need to customize the build commands. We also were surprised by CI _not_ catching this problem, so updates CI to actual do builds.
No CHANGELOG entry needed IMO.

Fix benchmarks to build w/ pyproject.toml

---

CHANGELOG.md
pystac/validation/stac_validator.py
tests/validation/test_validate.py

- #887
Closes #887 by returning all issues found during validation in the source parameter of the `STACValidationError`

return all validation issues

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
pystac/errors.py
pystac/item.py
pystac/item_collection.py
pystac/serialization/identify.py
tests/data-files/catalogs/invalid-catalog/catalog.json
tests/serialization/test_identify.py
tests/test_catalog.py
tests/utils/test_cases.py

- [pystac-client#130](https://github.com/stac-utils/pystac-client/issues/130) 
This creates a standardized message (which doesn't blow out the console) for `STACTypeError`s.

change STACTypeError to create short informative message

---

CHANGELOG.md
pystac/__init__.py
pystac/asset.py
pystac/layout.py
pystac/link.py
pystac/stac_io.py
pystac/stac_object.py
pystac/utils.py
tests/data-files/windows_hrefs/catalog.json
tests/data-files/windows_hrefs/test-collection/collection.json
tests/data-files/windows_hrefs/test-collection/test-item/test-item.json
tests/posix_paths/test_posix_paths.py
tests/test_catalog.py
tests/test_item.py
tests/test_layout.py
tests/test_link.py
tests/test_utils.py
tests/utils/stac_io_mock.py

- Closes #619 
- Closes #215 
- Link and asset HREFs are now always written with POSIX-style (`/`) delimiters whether on a POSIX or Windows system. This better aligns with the STAC specification (see [Matthias's comment](https://github.com/stac-utils/pystac/issues/619#issuecomment-1017926035)). 
- Addresses #215 by removing `_pathlib = os.path` from `utils.py`. Monkey patching `os.path` to behave as if on a Windows machine for testing is no longer needed since the full suite of tests now runs on Windows in CI.
Notes:
- Even though it is no longer used, I left the `JoinType` class and the associated `join_path_or_url` function in `utils.py` since users may be relying on them for other purposes. However, I also marked them as deprecated for eventual …

Always write `/`-delimited paths

---

CHANGELOG.md
pystac/__init__.py
pystac/extensions/classification.py
tests/data-files/classification/classification-landsat-example.json
tests/data-files/classification/classification_landsat_example.json
tests/data-files/classification/collection-item-assets-raster-bands.json
tests/data-files/classification/collection-item-assets.json
tests/extensions/test_classification.py

Closes #788
This PR adds the [Classification Extension](https://github.com/stac-extensions/classification) to pystac.

Add classification extension

---

CHANGELOG.md
pystac/item.py
pystac/link.py
tests/test_item.py

- #283
Add `get_derived_from` and `set_derived_from` to  pystac.Item

Add `get/add/remove_derived_from` to  pystac.Item

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
tests/test_catalog.py
tests/test_collection.py

- Closes #1138 
I didn't quite go so far as reverting, but I did make the change backwards compatible by not relying on the new kwarg internally. I ran the pystac-client tests locally and the one that was failing in https://github.com/stac-utils/pystac-client/issues/485 passes now.
Note: I didn't add tests.There should be only 2 lines that aren't tested (the ones in the TypeError blocks), so it seemed like more trouble than it was worth, but just let me know if you think they are necessary. 

Make sure that get_items is backwards compatible

---

CHANGELOG.md
pystac/extensions/eo.py
tests/extensions/test_eo.py

- Closes #275
This PR adds a new `get_assets` method on the `ItemEOExtension` class:
```python
import pystac_client
import planetary_computer
from pystac.extensions.eo import EOExtension
catalog = pystac_client.Client.open(
"https://planetarycomputer.microsoft.com/api/stac/v1",
modifier=planetary_computer.sign_inplace,
)
landsat = catalog.get_collection("landsat-c2-l2")
item = next(landsat.get_items())
eo_ext = EOExtension.ext(item)
eo_ext.get_assets()
```

Get assets by eo:bands common_name or name

---

README.md
docs/installation.rst
pyproject.toml

- Closes #1082
#1142 still relies on jinja2 being installed, so it is totally independent of this PR

Add optional jinja2 dependency

---

pystac/extensions/base.py

- closes #1060
`add_if_missing` should always be optional and default to False.  I don't think this needs a changelog

Ensure that `add_if_missing` is always be optional and defaults to False

---

docs/api/extensions.rst
docs/api/extensions/base.rst
docs/api/extensions/classification.rst
docs/api/extensions/datacube.rst
docs/api/extensions/eo.rst
docs/api/extensions/file.rst
docs/api/extensions/grid.rst
docs/api/extensions/hooks.rst
docs/api/extensions/item_assets.rst
docs/api/extensions/label.rst
docs/api/extensions/mgrs.rst
docs/api/extensions/pointcloud.rst
docs/api/extensions/projection.rst
docs/api/extensions/raster.rst
docs/api/extensions/sar.rst
docs/api/extensions/sat.rst
docs/api/extensions/scientific.rst
docs/api/extensions/storage.rst
docs/api/extensions/table.rst
docs/api/extensions/timestamps.rst
docs/api/extensions/version.rst
docs/api/extensions/view.rst
docs/api/pystac.rst
docs/api/serialization/common_properties.rst
docs/api/serialization/identify.rst
docs/api/serialization/migrate.rst
docs/api/validation/schema_uri_map.rst
docs/api/validation/stac_validator.rst
docs/conf.py

- Closes #446
autodoc can always stand to be decluttered more, but in this PR I tried to make things a little better by:
- removing inheritance from class docstrings
- adding autosummary to some key pages
I also added a few stubs for extension classes where the docs were missing.

Unclutter autodoc slightly

---

CHANGELOG.md
pystac/catalog.py
tests/test_catalog.py

Replaces #1141 
- Closes #345 
I think this covers the scenario described in the original issue of limiting the amount of objects that are iterated over. It made more sense to be to track that as a single number (items + catalogs + collections) and then to separately give a knob for changing whether or no we recurse into the children. 
That being said there are _lots_ of ways to tackle this. Anther approach could use a timeout rather than tracking number of objects at all.

Allow more configuration with `Catalog.validate_all`

---

CHANGELOG.md
pystac/asset.py
pystac/collection.py
pystac/item.py
tests/conftest.py
tests/test_asset.py
tests/test_collection.py
tests/test_item.py

- #911 
Add methods to `Asset`, `Item`, and `Collection` to support moving/copying/deleting assets and their referenced data files. 

Add move/copy/delete methods on Asset

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
tests/test_catalog.py

- #1159
Catalog: `add_child` and `add_item` return a Link object instead of None [#1159](https://github.com/stac-utils/pystac/issues/1159)
**Example:**
```py
import pystac
root = pystac.Catalog("root", "root")
left = pystac.Catalog("left", "left")
link = root.add_child(left)
link.extra_fields["datetime"] = "2020-01-01T00:00:00Z"
root.normalize_and_save("out_test", pystac.CatalogType.ABSOLUTE_PUBLISHED)
```
Creates:
```json
{
"type": "Catalog",
"id": "root",
"stac_version": "1.0.0",
"description": "root",
"links": [
{
"rel": "root",
"href": "/mnt/c/Dev/pystac/out_test/catalog.json",
"type": "application/json"
},
{
"rel": "child",
"href": "/mnt/c/Dev/pystac/out_test/left/catalog.json",
"type": "application/json",
"datetime": "2020-01-01T00:00:00Z"
},
{ …
```

Return Link Object after adding a child or item #1159

---

pystac/validation/__init__.py

There's a lint error generated with newer mypy versions.  This fix removes the erring annotation.

Remove faulty mypy annotation

---

CHANGELOG.md
docs/api.rst
docs/api/extensions.rst
docs/api/extensions/xarray_assets.rst
pyproject.toml
pystac/__init__.py
pystac/extensions/xarray_assets.py
tests/data-files/xarray-assets/collection.json
tests/data-files/xarray-assets/item.json
tests/extensions/test_xarray_assets.py

- #846 
EDIT: I removed the `open` method, so this is just a regular extension class now.
This PR implements an extension class for xarray-assets extension with a special `open` method for extended pystac.Assets as described in https://github.com/stac-utils/pystac/issues/846#issuecomment-1587441466
```python
import pystac
from pystac.extensions.xarray_assets import XarrayAssetsExtension
daymet_collection = pystac.Collection.from_file(
"https://planetarycomputer.microsoft.com/api/stac/v1/collections/daymet-daily-hi"
)
daymet_asset = daymet_collection.assets["zarr-abfs"]
xr_ext = XarrayAssetsExtension.ext(daymet_asset, add_if_missing=True)
xr_ext.open()
```

Xarray Assets Extension class

---

pystac/catalog.py

- Deprecation introduced in #1075
Quick fix to use the non-deprecated versions (thanks warnings!). doesn't need a changelog

Fix internal usage of deprecated function

---

CHANGELOG.md
pystac/item.py
tests/test_item.py

- Motivated by https://github.com/stac-utils/pystac-client/issues/548
When resolving an item's collection link, we should pass the item's root into `resolve_stac_object`. This situation can come up when bouncing around a STAC API, where you don't always have a full tree built up in your cache.

Collection link should be resolved with root

---

pyproject.toml
scripts/test

- Noticed that we didn't have this hooked up in #1172 

Make tests fail on warning

---

pyproject.toml

- Need release of https://github.com/kiwicom/pytest-recording/pull/110 to remove ceil
Doesn't need a changelog.

Ceil vcrpy

---

pyproject.toml
pystac/link.py
pystac/stac_object.py
pystac/validation/local_validator.py
tests/cassettes/test_item/test_non_hierarchical_relative_link.yaml
tests/test_item.py

Closes #1112
This is an attempt to address the unexpected and maybe undesirable behavior identified in #1112.  For this, we consider the case of a catalog tree which is defined using hierarchical links.  When serialized out as a self-contained catalog, using `to_dict` yields relative links for all elements.  Now, when we add additional links that have non-hierarchical `rel` types, but refer to entities which are in the hierarchical tree, the non-standard links are serialized with absolute hrefs.
For the following tree
```mermaid
flowchart TD
root -- child --> A
root --child--> B
A -. sibling .-> B
```
When we serialize `A`, we want to see
```json
{
"type": "Catalog",
"id": "a",
"stac_version": "1.0.0",
"description": "a",
"links": [
{
"rel": "root", …
```

Let non-hierarchical links to hierachical elements be relative paths for self-contained catalogs

---

CHANGELOG.md
MANIFEST.in
pystac/version.py

- We didn't include them in #1165 😢 
- Needs #1179 to fix the release workflow
Includes everything for a v1.8.1 release as well

Distribute jsonschemas

---

pyproject.toml

- Unblocks CI
- A quickfix until https://github.com/stac-utils/pystac/issues/1186 is fixed
**jsonschema** v4.18 deprecated `RefResolver`, so we'll need to update **pystac** to work around that deprecation. This PR is a quickfix to get CI working, and includes a note about the fix.
Doesn't need a changelog entry.

Allow a DeprecationWarning from jsonschema

---

CHANGELOG.md
pystac/link.py
pystac/version.py

- Accidentally removed in #1125
Discovered in **stactools** CI: https://github.com/stac-utils/stactools/actions/runs/5424579095/jobs/9864137816?pr=452#step:5:38. Includes a version bump to v1.8.2 to pick up the fix 🤦🏼

Explicitly re-export href

---

pyproject.toml

#1186 
with 4.18.1 and 4.18.2, jsonschema will raise an error. While we wait for the removal of `RefResolver` it would be safer to pin jsonschema with an upper bound to `<4.18`

set upper bound for jsonschema version

---

CHANGELOG.md
pyproject.toml

- https://github.com/stac-utils/pystac/issues/1186

pin jsonschema to <4.18 in validation and test

---

CHANGELOG.md
pystac/summaries.py
tests/test_summaries.py

- None
This implements two changes:
- Allow to pass a Dict with field names and summary strategies. Some people didn't realize they could set the `summaryfields` property so this makes it more obvious that you don't necessarily need to create a JSON file.
- Fix the foc rendering:
- Generally improve the summaries section a bit based on questions that I was asked during consulting.

Allow to pass a dict for the summarized fields, fix the doc rendering

---

docs/tutorials/pystac-introduction.ipynb
docs/tutorials/pystac-spacenet-tutorial.ipynb
pystac/catalog.py

- Introduced in #1075
Also, remove usages of deprecated functions.

Fix warning  message from get_all_items deprecation

---

pyproject.toml

We had to work around a breaking change to vcrpy for a bit, but that's fixed now. Includes some TOML-whitespace changes from my editor, hope that's ok.

Bump pytest-recording, remove vcrpy pin

---

.github/workflows/continuous-integration.yml
pyproject.toml

I realized recently that using `~=` and two digits for dependencies that start with `0.` is more-or-less meaningless, since it expands to `>=0.x,<1.0`. This updates to add a third digit for `0.*` dependencies.
This also fixes our bench check caused by `asv` breaking change in their CLI that popped up due to the dependency pinning problem. Doesn't need a changelog.

Use three digits for ~= v0.* deps

---

pyproject.toml

They appear exactly as-is on https://pypi.org/project/pystac/. Currently they look a little awkward:
No CHANGELOG needed.

Capitalize project.urls

---

CHANGELOG.md
pystac/collection.py
tests/test_collection.py

- Closes #1221
Thanks to @giswqs for the report! Since this will enable use of one of the larger open catalogs out there, we'll try to get a PATCH release out after this is merged.

Permissively deserialize temporal extents

---

docs/contributing.rst

**Description:** Fix typo in development installation instructions in contributing guide

Fix typo in dev install instructions

---

.pre-commit-config.yaml
docs/tutorials/pystac-spacenet-tutorial.ipynb

**Related Issue(s):** #1156
**Description:** Fix pre-commit configuration for black-jupyter, which was unintentionally skipping reformatting python within jupyter notebooks.

Fix black-jupyter pre-commit hook config

---

CHANGELOG.md
pystac/extensions/base.py
pystac/extensions/classification.py
pystac/extensions/eo.py
pystac/extensions/grid.py
pystac/extensions/label.py
pystac/extensions/mgrs.py
pystac/extensions/projection.py
pystac/extensions/raster.py
tests/extensions/test_classification.py
tests/extensions/test_projection.py

- Closes #1226
When loading extension data, extension implementations should use `startswith` (or whatever) to detect the presence of the extension, not an exact string match.

Allow future extensions to be used

---

CHANGELOG.md
pystac/catalog.py
pystac/item_collection.py
pystac/stac_object.py
tests/test_catalog.py
tests/test_item.py
tests/test_link.py

- Closes #1216
Functionally this worked, but the typing needed a fix.

Allow HREF when opening files

---

codecov.yml

- Closes #1244 
Doesn't need a CHANGELOG, infra-only.

Set codecov to be informational only

---

pystac/extensions/base.py

- Introduced during https://github.com/stac-utils/pystac/pull/1231
- Needs https://github.com/stac-utils/pystac/pull/1240 to get CI happy
Sorry should have caught this during review 🙇🏼, doesn't need a changelog

Use the pre-compiled version regex

---

.github/workflows/continuous-integration.yml
.readthedocs.yaml
CHANGELOG.md
docs/installation.rst
pyproject.toml
pystac/summaries.py
pystac/validation/local_validator.py

- Closes #1148 
I did _not_ run **pyupgrade** as that'll be really noisy, so I'm going to wait until the sprint is over and the repo has fewer folks hacking on it. I've opened a ticket to track that: https://github.com/stac-utils/pystac/issues/1235.

Drop python 3.8

---

CHANGELOG.md
docs/tutorials/adding-new-and-custom-extensions.ipynb
pystac/extensions/base.py
pystac/extensions/classification.py
pystac/extensions/datacube.py
pystac/extensions/eo.py
pystac/extensions/grid.py
pystac/extensions/item_assets.py
pystac/extensions/label.py
pystac/extensions/mgrs.py
pystac/extensions/pointcloud.py
pystac/extensions/projection.py
pystac/extensions/raster.py
pystac/extensions/sar.py
pystac/extensions/sat.py
pystac/extensions/scientific.py
pystac/extensions/storage.py
pystac/extensions/table.py
pystac/extensions/timestamps.py
pystac/extensions/version.py
pystac/extensions/view.py
pystac/extensions/xarray_assets.py
tests/extensions/test_custom.py

- #1061 
Deprecated `ExtensionManagementMixin.validate_has_extension` and replaced with `ExtensionManagementMixin.ensure_has_extension`. Calling `ExtensionManagementMixin.validate_has_extension` will raise a `DeprecationWarning` and call `ExtensionManagementMixin.ensure_has_extension`

Replace validate_has_extension with ensure_has_extension

---

CHANGELOG.md
pyproject.toml
pystac/validation/__init__.py
pystac/validation/stac_validator.py
tests/validation/test_validate.py

Include href when schema resolution fails

---

pystac/asset.py
pystac/collection.py
pystac/item.py
tests/extensions/test_xarray_assets.py
tests/test_item.py

- Closes #1199
- Refactor of #1168
I started working on #1199 only to discover it had already be fixed by #1168. However, I went an extra step and refactored the asset-modifying methods to an `Assets` protocol, so we only need to implement the logic once. The only hackey bit is the `get_self_href` stub, which is in place instead of trying to refactor all link-related logic to a `Links` protocol (which I tried but felt too disruptive).

DRY asset methods

---

CHANGELOG.md
pystac/collection.py
tests/test_collection.py

- #1267
* Allow `SpatialExtent.bboxes` to be a nested list of floats _and/or_ integers to reflect the STAC spec typing of `[[number]]`.
* In `SpatialExtent`, wrap `bboxes` in a list if passed as list of floats OR integers.
* In `TemporalExtent`, wrap `intervals` in a list if passed as a single interval.
While the linked issue discusses adding more robust validation/coercion of inputs, I opted to start simple because stricter checks on `bboxes` start to get a little gnarly:
```python
if all(isinstance(coord, (float, int)) for coord in bboxes):
self.bboxes = [cast(list[float | int], bboxes)]
elif all(
all(
isinstance(coord, (float, int)) for coord in bbox
) for bbox in bboxes
):
self.bboxes = cast(Bboxes, bboxes)
else:
raise TypeError(f"unexpected type …
```

Improve handling of `bboxes` and `intervals` 

---

pystac/extensions/base.py

These things are deprecated in v1.9, not removed then. Doesn't need a CHANGELOG.

Fix deprecation messages

---

CHANGELOG.md
pystac/collection.py
tests/test_catalog.py
tests/utils/test_cases.py
tests/validation/test_validate.py

- #
The patch fixes the use of the `utcnow` method that has been deprecated in Python 3.12.

Do not use the deprecated utcnow

---

docs/concepts.rst

- None
Currently the code examples use `Union` and `Any` without first importing the typing package. This change adds the missing import for 2 code examples.

Docs fix: added import for typing objects

---

CHANGELOG.md
pystac/item.py
tests/test_item.py

- https://github.com/stac-utils/pystac-client/issues/315
Not totally sure if this is a good idea, but I figured a PR would be a good place to hash that out. The only limitation I can see is that if you have a resolved target object on your link, it will not be resolved with you roundtrip it to pickle and back.

Make item pickle smaller

---

CHANGELOG.md
docs/concepts.rst
pystac/catalog.py
pystac/collection.py
tests/test_catalog.py

- https://github.com/stac-utils/pystac-client/issues/241
This PR enables setting a default layout strategy for a catalog. Users can either set the default layout strategy
when instantiating the catalog or defining a fall back strategy when subclassing Catalog.
Together with #1294, this PR is part of setting the foundation for enabling API transactions using `pystac-client`.

Default layout strategy for catalogs

---

CHANGELOG.md
docs/concepts.rst
docs/tutorials/how-to-create-stac-catalogs.ipynb

none
This fixes tutorial code that accesses S3, which probably broke with commit https://github.com/stac-utils/pystac/commit/01f71b15e91762557aa1d2c9374458c5dcef.

custom StacIO init needs to call parent init

---

pystac/html/JSON.jinja2
pystac/html/Macros.jinja2

- #1310 
Kind of hard to reproduce, but even if this is a noop in many cases the reduction in size will hopefully be compelling.
For a notebook containing an executed version of the following:
```python
search = client.search(
max_items=10,
collections=['sentinel-2-l2a'],
bbox=[-72.5,40.5,-72,41]
)
search.item_collection()
```
The saved size on this branch is 4.4M as opposed to 5.4M on main

Minimize css a bit and make it better at overriding jupyter defaults

---

.github/workflows/continuous-integration.yml
CHANGELOG.md
pyproject.toml

Test against Python 3.12 in CI and advertise it in our package metadata.

Test and advertise python 3.12

---

pystac/catalog.py

Replace called methods in docstrings with simple code blocks

---

CHANGELOG.md
pystac/stac_object.py
pystac/validation/__init__.py
tests/validation/test_validate.py

- n/a
Currently, performing validation on STAC objects with extensions that are not directly part of `pystac`, or that the schema is not yet published at the expected URI defined by the extension, is not convenient or obvious. 
In order to call `<STACObject>.validate()`, one has to either duplicate the operations done in `pystac.validation.validate_dict` to use their own validator or set it globally with `RegisteredValidator.set_validator` before calling `<STACObject>.validate()`. This PR adds a `validator` input to all the relevant functions to directly provide the validator to use for validation, with a local reference. This makes it easier to manage the "active" validator at the moment the `validate` method gets called.

add custom validator as input

---

pystac/extensions/grid.py

- n/a
fix grid extension docs on `code` property, which were not modified after copying from the MGRS extension (oops, my fault!)

fix gridcode pydoc

---

CHANGELOG.md
docs/api.rst
docs/conf.py
docs/tutorials/creating-a-landsat-stac.ipynb
pystac/layout.py
pystac/serialization/migrate.py
pystac/version.py
tests/test_layout.py

- # NA
Update the API Layout Strategy to optionally allow users to provide only the StacObject ID instead of the full object.
Add new methods to generate hrefs for API-specific endpoints such as `items`, `collections`, `search`, `conformance` etc.
Update documentation and link APILayoutStrategy in API Reference page.

Add more endpoints to APILayoutStrategy

---

CHANGELOG.md
pystac/item.py
tests/test_item.py

- Closes #1336 
- Relates to #960
`__getstate__` was doing too much work by trying to resolve the root. @jsignell we'll want to release a PATCH once this merges, as this will be a good fix to get out in the wild.

fix: don't transform_href in __getstate__

---

CHANGELOG.md
pystac/catalog.py
tests/test_catalog.py

- closes #1360 
The docstring states that this method is meant to traverse subcatalogs recursively.

Make `get_all_collections` properly recursive

---

CHANGELOG.md
pystac/extensions/classification.py
tests/data-files/classification/collection-item-assets-raster-bands.json
tests/extensions/cassettes/test_classification/test_apply_bitfields.yaml
tests/extensions/cassettes/test_classification/test_validate_classification.yaml
tests/extensions/test_classification.py

- Closes #1354 
- Adds the new `nodata`, `percentage`, and `count` fields
- Makes `description` optional
- Make `name` required
- Removes a copy-pasta double-check of the color hint

Implement classification v2.0.0

---

docs/index.rst

- Closes #1349 
The search box was embedded in the page, but that was not obvious and made the topbar search behave strangely. This PR makes the index page the same as the other pages.

Un-special-case search box on index page

---

pystac/extensions/datacube.py

Just a minor URL fix in a docstring
FYI: this was a quick edit in GitHub's online editor, so I did not really did anything of this PR checklist

Fixup url in Dimension.dim_type docs

---

CHANGELOG.md
docs/concepts.rst

Adds an example of a custom `StacIO` for reading/writing STAC objects from/to Azure Blob storage. I organized the existing S3 example and new Blob storage example into tabs to avoid cluttering up the docs:
I implemented this custom `StacIO` and thought it might be a nice to include an example for another cloud provider in the docs, but feel free to reject if this is unwanted.

Add example of custom StacIO for Azure Blob storage

---

.github/workflows/continuous-integration.yml
.readthedocs.yaml
CHANGELOG.md
docs/installation.rst
pyproject.toml

Numpy ended support Apr 05, 2024. We've done these in MINOR releases in the past, so if https://github.com/stac-utils/pystac/milestone/37 requires a MAJOR we'll want to get a MINOR out w/ this change first, I reckon.

Remove python 3.9

---

CHANGELOG.md
docs/api.rst
pystac/client.py
tests/test_pystac_client.py

- Closes #1334 
```python
from pystac.client import Client
```

Add convenience method for accessing pystac_client

---

.pre-commit-config.yaml
CHANGELOG.md
pyproject.toml
pystac/__init__.py
pystac/catalog.py
pystac/errors.py
pystac/extensions/mgrs.py
pystac/extensions/version.py
pystac/layout.py
pystac/provider.py
pystac/serialization/common_properties.py
pystac/serialization/migrate.py
pystac/stac_io.py
pystac/stac_object.py
pystac/utils.py
pystac/validation/schema_uri_map.py
pystac/validation/stac_validator.py
pystac/version.py
tests/data-files/get_examples.py
tests/extensions/test_custom.py
tests/extensions/test_scientific.py
tests/extensions/test_version.py
tests/posix_paths/test_posix_paths.py
tests/test_layout.py
tests/test_utils.py

- Should have been part of #1384
No functional code changes.

pyupgrade to 3.10

---

CHANGELOG.md
pystac/link.py

- Closes #1379 
We already have a [collection rel type](https://github.com/stac-utils/pystac/blob/28352e7c8932ee25f72c1eb74fd8516cd2a7ed73/pystac/rel_type.py#L18-L19), so this PR is just a small docs tweak to reflect that collection links don't have to be only for items.
It's not required, but it would be nice to move `{get|set}_collection` to `STACObject` from `Item`: https://github.com/stac-utils/pystac/blob/28352e7c8932ee25f72c1eb74fd8516cd2a7ed73/pystac/item.py#L260-L295
However, as documented in #1392, `set_collection` returns `self`, which makes it a bit more awkward to return from the `STACObject` base class. My instinct is to hold off for moving `{get|set}_collection`, and just create a tracking issue in the v2.0 milestone so that we can …

Update docs to reflect that collection rel type can be for anything

---

.pre-commit-config.yaml
docs/conf.py
docs/contributing.rst
docs/tutorials/adding-new-and-custom-extensions.ipynb
docs/tutorials/creating-a-landsat-stac.ipynb
docs/tutorials/how-to-create-stac-catalogs.ipynb
docs/tutorials/how-to-read-data-from-stac.ipynb
docs/tutorials/pystac-introduction.ipynb
docs/tutorials/pystac-spacenet-tutorial.ipynb
pyproject.toml
pystac/catalog.py
pystac/serialization/common_properties.py
pystac/serialization/migrate.py
pystac/validation/local_validator.py
pystac/validation/stac_validator.py

Since we already have ruff for linting, this gets one one fewer dep. Doesn't need a changelog.
Also includes a couple of tweaks to ape https://github.com/astral-sh/ruff-pre-commit/blob/main/.pre-commit-hooks.yaml more exactly but still use the system `ruff`.

Switch to ruff-format from black

---

CHANGELOG.md
pystac/item.py
tests/test_item.py

- Reported in https://github.com/stac-utils/stac-api-validator/issues/527
`collection` is listed as a top-level attribute for `Item`, but it is not set when there is no collection, leading to an attribute error when trying to access `Item::collection`.

Set collection to None in item constructor when there is no collection

---

CHANGELOG.md
pystac/extensions/eo.py
tests/extensions/test_eo.py

- Closes #1402 
Fixed simply by using `get` on the properties dict instead of the accessor.

Fix recursion error when eo band name is missing

---

.pre-commit-config.yaml
CHANGELOG.md
pystac/item.py
tests/test_item.py

- Closes #587
This PR fixes item field ordering in accordance with the order defined [here](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#item-fields). Additionally, I've fixed what appears to be a small configuration error in pre-commit.config.yaml such that ruff-format wasn't actually fixing ill-formatted files.

Fix item field ordering on `save_object`

---

CHANGELOG.md
pystac/common_metadata.py
tests/data-files/item/sample-item-asset-properties.json
tests/test_common_metadata.py

- #1378
Move roles to common metadata for STAC spec 1.1.0

Add roles to common metadata

---

CHANGELOG.md
pystac/collection.py
pystac/common_metadata.py
pystac/item.py
tests/test_common_metadata.py

- #1377
- #1381
- #1382
A collection of smaller updates for STAC 1.1.0 with regard to description, license, and datetime. I grouped these together as they were small changes, but can broken down if that's preferred. 

Update and clarify description, license, datetime properties

---

CHANGELOG.md
pystac/common_metadata.py
tests/data-files/item/sample-item-asset-properties.json
tests/test_common_metadata.py

- #1376
Moves keywords into common metadata for STAC spec 1.1.0

Add keywords to common metadata

---

pystac/utils.py
tests/test_utils.py

- #1369 
**Description:** Simple replacement of `str()` with `repr()`. This technically changes the output from a string to a quoted string, eg `foo` to `'foo'`. But I couldn't find any places where it'd matter.
This is such a minor change I wasn't sure whether to add to the changelog; should I?

replace str() with repr() in StringEnum & test it (#1369)

---

.github/workflows/continuous-integration.yml
.gitignore
CHANGELOG.md
pystac/utils.py
tests/test_catalog.py
tests/test_layout.py
tests/test_utils.py
tests/utils/__init__.py
tests/utils/os_utils.py

- #1470 
Python 3.13 nuances the use of `os.path.isabs` - https://docs.python.org/3/library/os.path.html#os.path.isabs
So I changed the test to reflect that

Issue 1470 paths windows

---

docs/tutorials/creating-a-landsat-stac.ipynb

Fixes a broken link in https://pystac.readthedocs.io/en/latest/tutorials/creating-a-landsat-stac.html#Adding-assets

Landsat tutorial: fix broken link

---

CHANGELOG.md
pystac/extensions/ext.py
tests/extensions/test_scientific.py

closes #1485 
It was indeed very straightforward

Access scientific extension on item using .ext

---

CHANGELOG.md
pystac/link.py
tests/test_catalog.py
tests/test_link.py

- closes #1482 
Not sure if throwing a different error counts as a breaking change :)

Better error message when link does not resolve

---

CHANGELOG.md
pystac/catalog.py
pystac/stac_io.py
pystac/utils.py
tests/test_catalog.py

- closes #1486 
Doesn't strictly disallow saving. Saving to a URL already throws an error if you are using the default stac_io so I think it is more appropriate to raise an error if you try to set the root to a non-url

Raise an error on APILayoutStrategy when root_href is non-url

---

CHANGELOG.md
pystac/catalog.py
pystac/media_type.py
pystac/stac_object.py
tests/test_catalog.py

- closes #1255 
- closes #1325 
* Allow media_type on get_links and get_single_link to an iterable
* Use `application/json", "application/geo+json" or None as the media_type for `get_root_link`, `get_child_links` and `get_item_links`

get_root_link/get_child_links/get_item_links: Ensure correct media types

---

CHANGELOG.md
pystac/extensions/projection.py
tests/extensions/test_projection.py
uv.lock

- Closes https://github.com/stac-utils/pystac/issues/1503
- Follow-on to discuss migrate-by-default here: https://github.com/stac-utils/pystac/issues/1504
If a STAC item is _not_ migrated to the latest version, it would be missing its `code` attribute. This means that `epsg` would be none, even if the incoming dicitonary had an epsg.
I'll want to release this as a bugfix when merged.
cc @Kirill888

fix: fall back to epsg

---

CHANGELOG.md
pystac/extensions/projection.py
tests/data-files/projection/another-1.1.json
tests/extensions/test_projection.py

Hopefully this, with https://github.com/stac-utils/pystac/pull/1509, will fix our backwards-compatability 🤞🏼 . We didn't catch this previously because our other proj v1.1 item had a `proj:wkt` set.

fix: fall back to epsg in crs_string, too

---

CHANGELOG.md
pystac/catalog.py
pystac/collection.py
pystac/item.py
pystac/stac_io.py
pystac/stac_object.py
tests/extensions/test_classification.py
tests/extensions/test_eo.py
tests/extensions/test_grid.py
tests/extensions/test_projection.py
tests/extensions/test_raster.py
tests/test_catalog.py
tests/test_collection.py
tests/test_item.py
tests/utils/__init__.py

- Closes #1504 
- Motivated by #1503
With increased heterogeneity of extensions in the ecosystem, especially breaking changes like [proj v2](https://github.com/stac-extensions/projection/releases/tag/v2.0.0), there's more and more schema allowed in a valid STAC value. Handling these in **pystac** is ... tricky.
On read+load, **pystac** has the concept of "migration", where fields on STAC objects and in STAC extensions are moved around and updated to the latest versions. Migration is currently ON by default when using `from_file`: https://github.com/stac-utils/pystac/blob/21a0bbbf1299e6e3323fea556b39f4ccad54e1f3/pystac/stac_object.py#L633
However, it is OFF by default when using `from_dict`: https://github.com/stac-utils/pystac/blob/21a0bbbf1299e6e3323 …

fix: migrate by default

---

CHANGELOG.md
pystac/serialization/identify.py
tests/extensions/test_eo.py
tests/serialization/test_identify.py

- Closes #1506 
The `min_version` and `max_version` should always be coerced to `STACVersionID` objects.

Make sure that VersionRange has VersionIDs rather than strings

---

uv.lock

**Description:** I rebuilt my environment and noticed uv updated `uv.lock`, seemed like a quick & easy PR.
Didn't update documentation nor the changelog since it's a small, internal change.

Update uv.lock for pystac 1.12.1

---

tests/test_collection.py
tests/test_item_assets.py
tests/test_item_collection.py

**Related Issue(s):** #993 
**Description:** Continued in the pattern for the previous 993 PR: Converted tests from unittest to pytest 

993 progress: convert 3 more files to pytest

---

CHANGELOG.md
docs/api/pystac.rst
docs/conf.py
pystac/catalog.py
pystac/collection.py
tests/conftest.py
tests/test_collection.py

- Closes #1254 
I ended up implementing this the opposite direction from the original proposal as mentioned in the ticket. There are probably more attributes that we can scrape off the items especially once #1521 shakes out.

Add `Collection.from_items`

---

.github/workflows/ci.yaml
pyproject.toml
src/pystac/asset.py
src/pystac/extent.py
src/pystac/item.py
src/pystac/stac_object.py
tests/test_extent.py
tests/test_item.py
tests/v1/conftest.py
tests/v1/data-files/item/sample-item.json
tests/v1/test_item.py
tests/v1/utils.py
uv.lock

- Starting on v2 buildout, testing how PRs look and work
Added the first v1 test back in, to show how this might work

feat(v2): first v1 test

---

tests/test_catalog.py
tests/test_layout.py
tests/test_link.py

**Related Issue(s):** #993 
**Description:** Convert `test_catalog.py`, `test_layout.py` and `test_link.py` to pytest. 

993 progress: Convert `test_catalog.py`, `test_layout.py` and `test_link.py` to pytest

---

tests/serialization/test_identify.py
tests/test_cache.py
tests/test_common_metadata.py
tests/validation/test_schema_uri_map.py

**Related Issue(s):** #993 
**Description:** Another round of conversion to pytest. In `test_common_metadata.py`, I assumed the several calls to `self.item.clone()` were unneeded because the original object was never used.

993 progress: convert last 4 files outside of extensions/

---

CHANGELOG.md
pystac/version.py

- Get https://github.com/stac-utils/pystac/pull/1512 out to release fix for https://github.com/stac-utils/pystac/issues/1506
I went back to the last commit w/o a adding change to make this a "true" PATCH. I'll cut the release pointing at this commit once approved, then resolve merge conflicts and merge this (not squash merge) back to **main**.

release: v1.12.2

---

CHANGELOG.md
pystac/extensions/projection.py
tests/data-files/projection/collection-with-summaries.json
tests/extensions/test_projection.py

- #1548
* Update the Projection extension's `migrate` method to migrate projection fields on Assets on Items and Item-Assets on Collections.
* Rename `test_migrate` to `test_migrate_item` and add `test_migrate_collection_item_assets`

Projection extension: migrate Assets on Items

---

pyproject.toml
pystac/stac_io.py
tests/test_stac_io.py
uv.lock

- Closes #1579 
This is a really simple tweak that supports v1 of urllib3. 

Support older versions of urllib3
